### ISSUE TITLE
12 month pages transcribed count

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1020]
On the statistics tab, before the leaderboard, let's add "Pages Transcribe -- Last 12 Months" with a 3 column layout (like the leaderboard) with 4 months per column and the count of pages transcribed next to the month name.

**Comment by saracarl** [comment]
The above is not the right approach.  We should do a view that is used in both the monthly mailer and in the owner dahsboard.  In the dashboard it should have a date picker.

**Comment by tbl73** [comment]
It turns out that using the view across both the owner dashboard and monthly email isn't really feasible, because the view in the owner dashboard relies heavily on external CSS files, which can't be processed by HTML email clients.  The datepicker is in the dashboard, and the same information will be provided in both places, but the monthly email can't just render the partial.

**Comment by benwbrum** [comment]
I believe that this is already accomplished through the collaborators tab.
