### ISSUE TITLE
Restricted collaborator visibility

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1043]
Restricted collaborators have bugs, in which we may show the "help transcribe" button to people who are not allowed to transcribe.

**Comment by benwbrum** [comment]
We need specific examples of this issue.

**Comment by saracarl** [comment]
This caused a problem today because USDA restricted their works in a popular collection that didn't have good instructions (they wanted to work on the instructions).  The works still look like this one the collection page:

![image](https://user-images.githubusercontent.com/708566/206505709-302682c6-7fb8-4e10-b600-9cdb418afe3d.png)

When you click on "help out" you are redirected to your dashboard.

If the work is restricted we should say "restricted collaboration" instead of "help out"
