### ISSUE TITLE
Support subjects within section headers

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1062]
From the Pelagios RDG narrative:

> FTP1 Enhance FromThePage’s markup for place hierarchies​: Currently
> FromThePage supports markup of subjects which can be categorized as places, as well as
> headers delimiting a section of text. We will extend this capability so that section headers
> may contain subject tags and appear inline as head words of an entry. This will allow
> hierarchal export of the place names and constituent places extracted from the entry.
> Administrative units will be categorized so that administrative hierarchy can be exported.
> The following example is from the English translation of Alcedo11:
> 
> > AUYAMAS, a river of the province and government of Santa Maria in the kingdom of
> > Tierra Firme, it is very abundant, rises in the snowy sierra, traversing in a rapid course the
> > valley of Upar, and after running 72 leagues, it enters the e. side of the river Magdalena.
> > 
> 
> We will mark up each section header (location name) with a section header specifier (===)
> as well as a subject link and then subject link each additional geographical subject within the
> section. (A section runs until the next section header is encountered.) Example:
> 
> > `===[[AUYAMAS]]===`, a `[[river]]` of the province and government of `[[Santa Maria]]` in the
> > kingdom of `[[Tierra Firme]]`, it is very abundant, rises in the snowy sierra, traversing in a
> > rapid course the `[[valley of Upar]]`, and after running 72 leagues, it enters the e. side of the
> > `[[river Magdalena]]`.
> > 
> 

Currently, FromThePage's mark-up supports section headers in an undocumented (and probably buggy) fashion.  Section headers certainly do not support subject mark-up.  We need to allow this kind of subject embedding and come up with some way to flag the fact that this is a lemma.

**Comment by benwbrum** [comment]
Add a visible difference to the page display that differentiates the section header.

**Comment by benwbrum** [comment]
Section headers can be head words in a block of text; we need to make sure that "works".  That means it should be displayed with a format like strong.  

TEI Export -- if 'pages are meaningful' is on, we use `div`s to wrap pages and some kind of milestone tag to express the headers.  If 'pages are meaningful' is off, we do not wrap pages in divs and instead use the section hierarchy to build divs representing the hierarchy.

**Comment by saracarl** [comment]
1)  Yes, similar to tables, subjects within a section should be associated with that section.  What that means implementation-wise is a new column on the `page_article_links` table and possibly some runoff-style/line-wise processing to set the context for the link processing.  See the existing tables/models recording sections on table cells for consistency.

2)  Tables are associated with a particular section because multiple tables can appear on a single page, with the section header contextualizing the table data.  On a page of financial accounts, the section header may describe a account holder's name and the table contents describe items purchased by that customer.

3)  Please add the section header to the subject exporter.  Just like we have columns for the work and page a subject appears in, we should add a column (actually 2) for the section a subject appears in.  Since section headers can contain subjects, the section columns in the export should probably be split into 2 columsn, one for verbatim text, one for canonical subject.

The result of tracking section headers in the data model and exposing them in the subject export will be an export that makes it easy to see which subjects are mentioned within an entry -- exactly what we need for LatAm.

4) At some point in the future--(we should probably open this in a separate issue)--the sections should be used for the work contents screen, providing a way to organize works by chapters/sections, etc.

**Comment by saracarl** [comment]
This issue includes the subject export CSV and we will spin off a separate issue for revising the TEI export.  That new issue should treat headers-in-separate-paragraphs (set off on their own) as chapter or section headings.  headers-inside (or leading) a paragraphy should be treated like headwords (however TEI lexicography does that).
