### ISSUE TITLE
Mrs.   -- links wrong

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#11]
subject linking for "Mrs." links to something wrong.  (a real subject, but not the person in question..)  Maybe the first "Mrs." defined.

**Comment by tbl73** [comment]
I'm unable to recreate this one - do you have any more information?

**Comment by benwbrum** [comment]
I think the problem here was that on one page a user would type `[[John Smith|Mr.]] and [[Jane Smith|Mrs. Smith]]`, then on another page used Autolink on `Mr. and Mrs. Jones` and was surprised the first title linked to a different person.  We thought about adding a list of stopwords to Autolink to avoid suggesting really common stuff like this.

**Comment by tbl73** [comment]
I added a list of stopwords to autolink so that these things aren't suggested.  Included in autolinking branch.
