### ISSUE TITLE
transcription fields: add "description" type for transcription fields

### ISSUE THREAD

**Issue by AustinCarr** [benwbrum/fromthepage#1152]
<img width="669" alt="description" src="https://user-images.githubusercontent.com/1855345/43527946-ce64d066-9575-11e8-9966-e640a12ebb6b.png">

It's currently awkward writing labels for some fields, because the form has descriptive text that has no actual input associated with it.

In the example above, the "Trained or stationed" text has to be put into the "school, ship" label, which is awkward. My suggestion is to create a new "description" transcription field type that has no input, but can be put on the form to help give context to other inputs.

**Comment by benwbrum** [comment]
If I understand correctly, unlike #1153, this is text that was on the original printed form -- instructions to the "author" of the text, rather than to the present-day transcriber.

I'd like to talk more about how the data is intended to be used, and what different projects might want out of this.  Alabama is to creating a spreadsheet from the original forms which they can use to update their metadata records.  As such, having a record of instructions (or even labels) is not useful to them, since the labels will appear as spreadsheet headers and the in-line instructional text is the same on all texts.  It seems like the use case at the Library of Virginia is very different, and that LVA would like the entire form to be represented in the output of the process.  That output would be similar to a typographic facsimile; the export could be printed out and read, without having to consult the original document.  In addition, that export is probably better done in a textual format like HTML or TXT than in a spreadsheet.

Does that sound correct to you, @AustinCarr?  If so, we'd want to suppress `description` fields in the CSV export, but record them in the `xml_transcript` for each page and make sure that the export shows them properly.  But I want to make sure my assumptions about use case are correct, first.

**Comment by AustinCarr** [comment]
You're correct about it being instructions to the "author" of the text, and you're also correct that our use-case is more similar to creating a searchable digital copy of the form, but I don't think we want to suppress the description fields in the CSV export.

That sort of data is still good for giving context to the other headers, and is useful to have when creating searchable metadata. In addition, I don't think that having that information in the CSV hurts anybody else's effort in any meaningful way.

Scripts that need to read particular headers from the CSV can simply ignore the description fields.  But scripts that use them to create the metadata will be out of luck if they're suppressed.
