### ISSUE TITLE
Create Editor Dashboard

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#118]
The goal of this task is to stub out a new screen.  Ben will fill it in with real data after it is stubbed out.  This should be a new View under the Dashboard Controller.

If a user is logged in the "Home" link should take them to a new screen, which is a dashboard designed for Editors/Volunteeers/Transcribers.

This screen lets them manage their work and see important updates about work they are interested in.

We need the following sections 
* My most recent edits (last 3 pages edited, goal is to let the user resume work where they left off.)
* Information about work other people have done on projects they have contributed to.  
   * Statistics for last three works they have contributed to (+ a "show all" link at the bottom)
   * Activity stream from collections they've worked on.  Goal is here: "What have those idiots messed up now?" or "Did anyone ask questions about something I've worked on?"  or "Did anyone answer my question?"  Show last 20 activities + a show all link.  (Similar to the watchlist in wikipedia.)
* New owner activity in collections I'm interested in.  (This is an 'official' view of the project -- is there more work to do?)

**Comment by kolking** [comment]
@saracarl could you please explain the last section:

> New owner activity in collections I'm interested in. (This is an 'official' view of the project -- is there more work to do?)

The main question is how the user will select a collections he is interested in?

**Comment by saracarl** [comment]
"Interested in" = has commented, transcribed, or taken some other action on the work/collection.  I think we'll work backwards from their activity stream to define this.  

Question for @benwbrum -- what does a user who hasn't transcribed or commented get associated with a work?  Do we tracking "viewing" as an action?   There's also the "I followed a link to get to this collection/work" -- maybe in that case we should show a work generic dashboard of some sort?  (What would a "work generic" dashboard look like?)

**Comment by benwbrum** [comment]
What we're fundamentally doing is creating a watch list, akin to Wikipedia's or Github's.  Editing a collection (or taking any other action on a collection that creates a deed) has the effect of adding that collection to a user's watch list.  We'll need to give this some thought to make it perform well, but I've got a few ideas.  

If a user wants to watch a collection and hasn't edited it--not a scenario I see happening very often--then we may add a "watch" action for logged in users that would manually add that collection to their watch list.

**Comment by kolking** [comment]
@saracarl @benwbrum could you please review this section?

Local url is http://localhost:3000/dashboard/watchlist

It divided into 2 tabs - "Watchlist" and "Your Activity". Watchlist shows 5 collections based on the current user's activity. For each collection it shows last 5 activity records. If user didn't make any activity yet, it will show first 5 collections. I'm not sure it's right, alternatively we can show a message saying that watchlist is empty because you didn't performed any actions yet. Please let me know your thoughts.

Your Activity shows the last actions for the current user - up to 10 recent page edits, 10 recent article edits, 10 recent notes. This is the place where they can resume work where they left off. At the right side it shows activity stream of other users (excluding the current user) with a link to show more.

**Comment by benwbrum** [comment]
We're looking at it now.

**Comment by benwbrum** [comment]
Okay, this is a very good start.  I had a long conversation with a user this weekend about this feature, and need to spend more time sketching out my thoughts and adding some back-end code for you  to use. 

Please wait on further work on this story until I get that added and update this.

**Comment by benwbrum** [comment]
*Raw notes on the watchlist -- no action needed yet*

In a lot of cases, the watchlist is not quite an activity stream -- it's not a chronological *list of the changes* that have been made to objects on the site, rather it's a chronological *list of objects that have changed* on the site.  See this example from Wikipedia, which lists one changed page per list item, with a note about its most recent change -- regardless of how many changes have happened to that page:

![wikipedia_watchlist](https://cloud.githubusercontent.com/assets/199961/7107978/4677eff2-e13d-11e4-874b-06d3906dc5e7.jpg)

**Comment by benwbrum** [comment]
*Raw notes on the activity stream -- no action needed yet*
An activity stream from the Transcribe SI site -- power users report that this is the very first thing they check on the site, so that they can fix anything that newer users have broken.

See the "Latest Updates" section at https://transcription.si.edu/

**Comment by kolking** [comment]
https://transcription.si.edu/ - it looks pretty close to our activity stream

**Comment by saracarl** [comment]
Close out this issue; finishing the details in issue #378
