### ISSUE TITLE
Add "processing" spinner to IA imports

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#119]
For long-running Internet Archive imports, we need to add a spinner (or some other visual cue) to let the user know that processing is happening so that they will wait.

The two places I noticed this today were:
* On a second import of the same IA work, we warn the user that they may have imported this work before.  When they press "continue", several seconds pass before they are presented with the screen to review the staged IA work.
* When the user views the staged IA work, and pressed "Publish to FromThePage", several seconds pass.

**Comment by kolking** [comment]
Yes, I've also noticed yesterday that the import process could take some time. I think we should make something like a global busy indicator that will shade the page and show the spinner in the middle.

**Comment by kolking** [comment]
@saracarl on a second import of an IA book that was already imported before, we show that confirmation and if the user click "Continue" we don't simply redirect him to the staged IA work. Instead of that, a new copy of the same IA book created and then we redirect the user to that newly created copy. Is it the right behavior?

**Comment by benwbrum** [comment]
Yes. Some times new project owners make mistakes and need to start their import from the beginning.

**Comment by kolking** [comment]
Ok, got it.
