### ISSUE TITLE
Activity Stream ("show more") doesn't work for document sets

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1216]
Here's a document set:  https://fromthepage.com/lva/richmond-va

Click on the "Show More" for the Notes and you are taken here: 
https://fromthepage.com/deed/list?collection_id=492

Which is blank.  It's blank because the "collection" is a document set.  An actual collection works (i.e. https://fromthepage.com/deed/list?collection_id=1)

We need deed/list to work for a document set as well as a collection.

**Comment by lortza** [comment]
@saracarl I am having trouble reproducing this locally. Steps I'm taking:
- Find a document set in the console:` DocumentSet.last`
- Grab its `id` => 101
- Make sure it has some activity (added a note and transcription)
- Go to the url using that document set's id: http://localhost:3000/deed/list?collection_id=101
- See activities in the stream

![Screenshot 2018-10-19 15.28.51.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ba00ccd9e0f8c0011902af3/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417773e785de37a25cbb170f1172a43434d0eee1e020a17b8eb8339a3b23a76db5b5ee9d8655921946f11aeb8821bbb54b376df5d99a4fedb1294b7607caddecd5d340c041f83fe5836a99043c851f34be84b5cb65e.png)

**Comment by benwbrum** [comment]
Ben to get a recent database dump

**Comment by saracarl** [comment]
This may be the same issue:
A user doesn't see any deeds for work done on a public document set in a private collection because the deeds are only associated with the collection and they don't have permission to see them.

**Comment by benwbrum** [comment]
I think that the right thing to do here is to fully support document sets for deeds.

To do:

- [ ] Create a migration that adds `document_set:references` to `deeds`
- [ ] Add a `has_many :deeds` association to `DocumentSet`
- [ ] Modify all the `record_deed` call-backs to check if `@collection` is a document set; if so, record `@collection.id` in `deed.document_set.id`.  (We probably already have code that does the check, as we are correctly resolving the document set's collection.
- [ ] Modify the `deed_list` partial or the `render_deeds` helper to check for a document set and pull the deeds from that set instead of the collection
- [ ] Modify the `deed` template to pass a document set to its `link_to` URL helpers instead of the collection, if one is present.
- [ ] Verify that prerendering works correctly.
- [ ] Verify that collections still show document set edits

**Comment by saracarl** [comment]
Behaviors we need to implement at each possible view:
- [ ] FindAProject:  only show public deeds
- [ ] Collection:  Don't show collection/docset name (deed can be on collection or any associated docset)
- [ ] Document Set:  Don't show collection/docset name  (make sure deed is on docset)
- [ ] User Profile:  Only public deeds by user (??)
- [ ] Collaborator Dashboard:  Show all deeds by user.  If user doesn't have access to work of deed, strip tags.  If user has access to work, include collection or docset they have access to
- [ ] User Activity Emails:  I think this should be the same as the collaborator dashboard.
- [ ] Document Added Emails:  Only send if user has access to the added work.
