### ISSUE TITLE
guest user redirected to site home screen

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1234]
LVA is reporting instances of transcribers being redirected to the FromThePage home screen/project listing.  This redirect is the default behavior within the application when permissions error is encountered, and sometimes also when a user logs in.

The problem seems to be related to guest users marking pages blank.

We need to reproduce the issue and fix it.

**Comment by saracarl** [comment]
More details from LVA:

_One *new* issue that we're seeing is, when logged out, if you click on a work and then page and then transcribe as guest - it takes you back to the From the Page homepage, rather than reloading the page with the form fields. When we were testing this earlier, this was not the case...any ideas why that might be happening? We've tried it on three computers in Chrome and Firefox with this same result. For tomorrow, it seems safest to make a test user account so that each of our volunteers don't have to sign up just to try it._

**Comment by saracarl** [comment]
I just verified a guest user can transcribe and mark pages as blank without any errors in a field based transcription as well as a full text transcription.

**Comment by saracarl** [comment]
Sent the following to LVA:
_I just tried to recreate the "guest user gets send to the FromThePage landing page when marking pages as blank" issue and I couldn't.  (You can see my notes here:  https://github.com/benwbrum/fromthepage/issues/1234)  In order to work this, we'll need more details -- exactly which collection/document set/pages, what steps it takes to reproduce the issue._  

I'm closing this issue until we receive reproduce steps and then we will reopen it.
