### ISSUE TITLE
Add pager instead of "older" link in the activity log

### ISSUE THREAD

**Issue by kolking** [benwbrum/fromthepage#124]

**Comment by saracarl** [comment]
Ok, I don't think paging with page numbers works here once you get over a certain amount of data (it's just too much).  What if we used the "show more" that you get in the right sidebar activity stream on http://localhost/app/dashboard/editor  ?

![activity_stream_paging](https://cloud.githubusercontent.com/assets/708566/7107922/40687e80-e13b-11e4-8a85-fa13904d91e8.jpg)

**Comment by kolking** [comment]
@saracarl I agree that page numbers here doesn't make a lot of sense, I made it to keep our data grids consistent. Ideally, we should add a date/period filter here, to show activity by months for example. What do you think of this idea?

**Comment by benwbrum** [comment]
Let's think a bit about the likely use cases.

Users can already view the history of edits to a work, an article, or a
page.  That should be enough to serve the purpose of the project manager or
academic researcher who wants an audit trail of the work which has been
done.  (Incidentally, if we don't paginate work history, we should open a
new story for that.)

The activity log of a collection (or the site) answers a different set of
questions:  What's happening now?  What's happened in [project which I care
about] since I was last here?  Did anyone new join the project and make
mistakes/vandalize pages/ask questions which I should review?

Those questions are best answered with a view which prioritizes recent
activity, but allows linear inspection into past activity.  It's hard for
me to imagine a scenario where an editor wants random access to, say, all
the activity that happened 7 months ago, but not 6 or 8 months ago.

So I suspect that the pagination here is appropriate for the use case.
What do you think, @saracarl?

**Comment by saracarl** [comment]
I think a "Show More" option, like on the right hand side of http://localhost/app/JuliaBrumfield that lets you keep going "back" but doesn't really give you a specific page or set of pages would be most appropriate here.  

It's the cleanest UI, but lets a really persistent person go back as far as they want.
