### ISSUE TITLE
Don't lose transcribers after last page of work

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1331]
LVA says:  "Users are often able to work through a document, but get stuck at the last page going "now what?""

I think this also brings up an import use case "How do we direct a transcriber to more works when they transcribe the last page of a work?"  That one's going to take more thinking, but I think it's an important idea to keep volunteers in "flow".

**Comment by saracarl** [comment]
So we should use the new field on a work that @jackweinbender introduced for performance to direct people to the next page of the least transcribed work in the same collection after they have finished a work.  We should include a flash message that says:

"Congratulations!  You've completed %{work.name}!  Thank you.  
We're sending you to %{new_work.name} if you'd like to keep transcribing."

What do we do if there isn't another appropriate work to transcribe in this collection?  (nothing might be OK for now.)

**Comment by benwbrum** [comment]
From a customer email yesterday:

_With this set of birth certificates, there are a lot of backs of the documents with nothing to transcribe (they were imaged due to policies related to complete copies). So I used the "mark blank" feature. I noticed though that once I marked a page blank, I was redirected to the Overview tab. So I had to click on the Transcribe tab (before or after advancing to the next page) in order to start transcribing again._
