### ISSUE TITLE
referral link to include owner/collection/work

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1370]
USHMM asked for a way to link folks directly to a work/collection and to make sure they get there after signing up on FtP.

My idea was a new deed type "joined" that would show the material on their dashboard and show them in the collaborator list.

Ben's idea was a "next URL" parameter passed in to the registration link.

Third idea:  Save from the session what landing page they came from. (we have this with Ahoy.)  Perhaps add this to the "joined" deed.

**Comment by benwbrum** [comment]
We want to capture the fact that a person came in from an external link (i.e. through a customer's social media or email) and where they landed (i.e. what collection or work they came to).  This is already captured by Ahoy in a landing page column.  We want to record this by storing it in a new "joined" deed (probably publicly visible) when a user's account is created or when an already registered user clicks on a project they haven't joined yet.

This data should be reused when a user hits the Dashboard--if they have never contributed to anything, this should send them to something akin to the organization's home page.

The data should also be reused in the contributor page for an organization/project, but that will be automatic if we use the deeds table.

Consider implications of regular clean-ups of the Ahoy table.

**Comment by jackweinbender** [comment]
So, now that we have the redirect stuff working properly with tests (#1417), we can start thinking more about this side of things.

As I mentioned in the chat, I think it may be time to introduce the concept of "following" or "watching" a project. Looking at the code, in fact, this is how we describe the user dashboard, `dashboard/watchlist`. Right now we populate that with the most recent five projects that the user has contributed to (and the five most recent deeds for each of those) Logging a "joined" or "watching" deed would also populate these, which I think is a good approach.

Which leaves the matter of how/when to log such a deed. There are a couple concerns I have:
1. We shouldn't be able to log more than one "join" deed for any given user/project combination. This isn't complicated, but we would have to enforce it in the business logic, rather than at the model-level (i.e., we can't enforce uniqueness of only one deed type).
2. If users still have to manually "join" a project, we haven't gained much re: the original problem. On the other hand, automatically joining a project if the user comes from an external referrer seems perhaps a bit heavy-handed.
3. This page currently only shows *collections* (and docsets), so if we want to log "joined" deeds to an organization, we'll need to be able to display that. Also, I don't think there is a way to associate a deed with a user as the direct object of the deed (for lack of a better term).

Maybe the best way to do this would be to just take the user/collection info from the path of the page that the new user is on when they register (we have this in `session[:user_return_to]`) and log the deed then. For most users, this will be the same organization/collection that they were referred to from the external link. For users who weren't on an organization/collection page, we can just show the "find a project" stuff (or better yet, just redirect them to that page).

These are my thoughts on the matter.

**Comment by jackweinbender** [comment]
From Slack, we decided:
1. It should be a "joined" deed
2. the Join deed should be connected to a Collection
3. the Join deed should be public
4. new Users auto-join based on Ahoy's data---the logged landing page.
5. "joined" users should show up in owner emails and stats, even ones who don’t transcribe.
