### ISSUE TITLE
after account creation better redirect

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1373]
This needs a lot of testing to see what the actual behavior is.  See #980 

Defined the actual behavior we want.  "Not getting lost" is the first bit, redirect to either "find a project" or possibly user dashboard (probably after we implement the "add to a collection" sign up link feature in #1370 )

**Comment by saracarl** [comment]
With the new confirmation emails, we'll need to make sure email redirect to the right place, too:

https://github.com/plataformatec/devise/wiki/How-To:-Add-:confirmable-to-Users#redirecting-user

**Comment by jackweinbender** [comment]
So, my manual testing indicates that our redirects all still work for normal users---and that goes for both new sign ups and logins. Users are generally returned to the page they were on previously.

**Sign-ins:**
```
Admin:   Always returned to admin dashboard
Owners:  Returned to previous page, defaults to owner dashboard
Users:   Returned to previous page, defaults to user dashboard
```

**Sign-ups:**
```
Admin:   N/A
Owners:  Always redirected to /dashboard#freetrial
Users:   Returned to previous page, defaults to root path
```
I think the only change that needs to be made is the behavior of the defaulted user sign-up. This is the "getting lost" path that we need to address first.

**Proposed Behavior**
New Signups should be redirected to the page they were on, but when that is not available, they should either:
1. Be shown their dashboard with projects that they have worked on (this is possible with new users because of the "guest" accounts), or 
2. If they haven't done any work, they should be redirected to the "find a project" page (as suggested above).
