### ISSUE TITLE
Better error message on bad CONTENTdm import

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1422]
Currently, if a user tries to import a compound object from CONTENTdm that doesn't work (see examples in #1409), they get an unfriendly "Please enter a valid IIIF manifest URI" message, which totally confuses them.  In a lot of cases, they get the error message because CONTENTdm doesn't supply a IIIF manifest for the item; perhaps because it's a single item or because it's in a content type CONTENTdm hasn't implemented IIIF for.

We need to do a better job of presenting friendly error messages.  In particular, we should say "No IIIF manifest exists for CONTETNdm item #{original_cdm_uri}." if that's the case.

**Comment by jackweinbender** [comment]
Thinking through the use cases here...

If it's a malformed Cdm url, I guess we can throuw the normal error. But in cases where there seems to be no IIIF manifest, should we instead "bump" them up a level? For instance, the problem we had in the #1409 issue; rather than just telling them there is no IIIF manifest there, should we return the `collection` listing (supposing it's there) with a message that the work couldn't be found, "but it might be in the list below". Mutatis mutandis for collections -> Repos.

**Comment by jackweinbender** [comment]
Oh, I see I misunderstood your suggestion. The issue isn't malformed URIs but rather cases where the URI is well formed, but doesn't produce a good manifest.

**Comment by benwbrum** [comment]
The most common use case here is one in which a user has created an object in CONTENTdm for which IIIF is unsupported -- usually a PDF.  They are working on adding support for these objects--in fact they'd love to hear anytime a user gets this error--but don't have them yet, so we really have to refer the user to OCLC.

So something like "We're sorry, no IIIF support exists for this object in CONTENTdm yet".  (And logging a `.info` message with an easy-to-grep string and the manifest URI that was attempted would be something we could hand to OCLC.
