### ISSUE TITLE
Restyle page version comparison

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#150]
Per page 8/23 in the UI Mock Ups.

http://96.126.116.203/app/page_version/show?page_version_id=6241

**Comment by kolking** [comment]
I've also added the functionality to visually highlight the changes between the selected revision and the current page version. Here is the screenshot:

![image](https://cloud.githubusercontent.com/assets/4656448/7266404/c566f5f8-e8b1-11e4-8ee8-824926c33d8d.png)

Please review and let me know your thoughts. I don't really like the checkbox to toggle between normal and diff modes, but it's just a quick solution.

**Comment by benwbrum** [comment]
I'm delighted -- it's something I've wanted in the tool for years.  I think
there's no need to toggle the changes off -- they can be on all the time,
and we can remove the checkbox.

Ben

**Comment by kolking** [comment]
@benwbrum thanks Ben, I'm glad you like it. I'm not sure that we should always show it in the diff mode because of the following:

1. I can turn it automatically on after page loaded, but the diff is performed by javascript on the client-side so there will be a noticeable flickering - it will show the current page version text and then after some delay show the changes. From the user's point of view it's not clear and could be confusing.
2. Since the diff tool works with the plain text I cannot restore the subject links for the diff mode.
3. It will be impossible to see the current version of the page here (as it is, without diffs).

I would recommend to keep the ability to switch the view mode, we can make the diff mode on by default if you like it more.
