### ISSUE TITLE
more features for viewing images

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1526]
A transcriber asks:

I’d like to see more features for viewing the images. I’ve seen other sites, eg Ancestry.com where you can invert the image colors, rotate the image, and change the contrast.

**Comment by saracarl** [comment]
Can we investigate if openseadragon supports image manipulation options like invert and changing the contrast?  

Related to #1531

**Comment by saracarl** [comment]
Here's an extension for OSD that does a lot of different image enhancements:
https://pages.nist.gov/OpenSeadragonFiltering/

Here's a page that a user tried to enhance themselves:
https://fromthepage.com/display/display_page?page_id=1195334

And their attempt:
https://twitter.com/2021funnies/status/1344267160781250560?s=21

We should:
1)  decide which of the image enhancement options makes the most sense for documents, based on how useful they are on this document.
2)  figure out how to add buttons to OSD to offer this/these image enhancement options.  (Contributing back to the extension)

**Comment by mulcare** [comment]
I'm very interested in this as well. I've had several collaborators ask if it was possible to adjust the brightness and/or contrast of a page, allowing them to more easily work with faded or otherwise difficult to see words and letters.

(As an aside, this is kind of a funny/interesting feature: isn't this essentially what OCR programs do for printed texts as part of the process of identifying letterforms?)
