### ISSUE TITLE
Too many "still_editing" calls

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1593]
A project owner reported some 500 errors.  I don't think this is related, but it does seem to be a problem:

![Capture](https://user-images.githubusercontent.com/708566/71690617-d4e85280-2d6a-11ea-932a-c9ff6af527a2.PNG)

Diary_pages_1914_04 | 23
-- | --

**Comment by benwbrum** [comment]
Also, we need to remove the `still_editing` action from Ahoy.

**Comment by benwbrum** [comment]
Issue 1) is that still editing seems to be happening too often.  I'm not sure we can fix this, since the code looks fine.

Issue 2) is that Ahoy is logging `still_editing`, which messes up the contributor tab numbers.  We need to stop logging this to Ahoy, and we need to create a migration to delete the `still_editing` ahoy events.
