### ISSUE TITLE
"Find A Project" page performance is slow

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1675]
@jackweinbender Can you do some rack miniprofiler analysis on this page and share what you find?

**Comment by jackweinbender** [comment]
Ok,here's what I've got.

The offending query is---contrary to my intuition---how we're selecting Deeds for the recent activity ticker and it runs pretty consistently in 4-8 sec on my local machine:
```
SELECT
    `deeds`.*
FROM
    `deeds`
    INNER JOIN `collections` ON `collections`.`id` = `deeds`.`collection_id`
    INNER JOIN `users` ON `users`.`id` = `deeds`.`user_id`
WHERE
    (collections.restricted = 0)
    AND `users`.`deleted` = 0
ORDER BY
    deeds.created_at DESC
LIMIT
    20;
```
I guessed that the issue was an index problem (and it may be), but we seem to have pretty thoroughly indexed Deeds:
```
  add_index "deeds", ["article_id"], name: "index_deeds_on_article_id", using: :btree
  add_index "deeds", ["collection_id", "user_id", "created_at"], name: "index_deeds_on_collection_id_user_id_created_at", using: :btree
  add_index "deeds", ["collection_id", "user_id"], name: "index_deeds_on_collection_id_user_id", using: :btree
  add_index "deeds", ["collection_id"], name: "index_deeds_on_collection_id", using: :btree
  add_index "deeds", ["created_at"], name: "index_deeds_on_created_at", using: :btree
  add_index "deeds", ["note_id"], name: "index_deeds_on_note_id", using: :btree
  add_index "deeds", ["page_id"], name: "index_deeds_on_page_id", using: :btree
  add_index "deeds", ["user_id"], name: "index_deeds_on_user_id", using: :btree
  add_index "deeds", ["work_id"], name: "index_deeds_on_work_id", using: :btree
```
Albeit, the subtleties of db indexing are lost on me, so there could be problems with the property ordering, etc.

The slowness, so far as I can tell, relates to the fact that we seem to be having to use a Temp table and Filesort for this query (maybe this is caused by missing an index?). in particular, it seems that the collection `JOIN` combined with the `ORDER BY` clause makes this slow. Removing either component makes the query run almost instantaneously:
```
-- 0.001 sec
SELECT
    `deeds`.*
FROM
    `deeds`
    INNER JOIN `users` ON `users`.`id` = `deeds`.`user_id`
WHERE
    `users`.`deleted` = 0
ORDER BY
    deeds.created_at DESC
LIMIT
    20;
```
Or
```
-- 0.001 sec
SELECT
    `deeds`.*
FROM
    `deeds`
    INNER JOIN `collections` ON `collections`.`id` = `deeds`.`collection_id`
    INNER JOIN `users` ON `users`.`id` = `deeds`.`user_id`
WHERE
    (collections.restricted = 0)
    AND `users`.`deleted` = 0
LIMIT
    20;
```
And, indeed, in both of these later cases, there are no temporary tables created and Filesort isn't used. So, I've boiled it down to the simplest form of the query that I could manage while still maintaining the performance bug. Note, I've even managed to remove the `WHERE` clauses:
```
-- 6-7 sec consistently on my machine
SELECT
    `deeds`.*
FROM
    `deeds`
    JOIN `collections` ON `collections`.`id` = `deeds`.`collection_id`
ORDER BY
    deeds.created_at DESC
LIMIT
    20;
```
So, I'm not sure where this leaves us. But these are my preliminary results.
