### ISSUE TITLE
inactive projects have "start transcribing" button

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1677]
Inactive projects can't be transcribed, so they shouldn't have a "start transcribing" button on them.  

They should also not have a "Pages needing transcription" or a "Pages needing review" button.

**Comment by isabelabarton** [comment]
This one defines inactive work so I think I could use that further down in the code.
https://github.com/benwbrum/fromthepage/blob/04742427e4d1702699da558ccb08a27fa838293a/app/helpers/collection_helper.rb#L72

This one is talking about things that shouldn't be displayed in inactive collections which is what this issue is talking about.
https://github.com/benwbrum/fromthepage/blob/0d740cd7f9c1ec95964fd081e5ef1fca2e420503/app/views/shared/_page_tabs.html.slim#L6

This one is probably less likely but it has an if statement separating active collections from inactive ones so maybe I could put something under it. An if/then statement?
https://github.com/benwbrum/fromthepage/blob/1ae2aea58ffae54e3707a8ca5c1868f961654a58/app/views/collection/edit.html.slim#L195

**Comment by saracarl** [comment]
You'll want something similar to 
https://github.com/benwbrum/fromthepage/blob/0d740cd7f9c1ec95964fd081e5ef1fca2e420503/app/views/shared/_page_tabs.html.slim#L6
but you'll need to add the same if statement around each of the three buttons.  It might be as easy as that.  ;)

**Comment by isabelabarton** [comment]
https://github.com/benwbrum/fromthepage/blob/79fc777bf8be612cee551eede0691bf066dea94e/app/views/display/_multi_page.html.slim#L27

"if @collection.active?" above all of these buttons?

**Comment by benwbrum** [comment]
Yes, or you can modify the `else` to an `elsif @collection.active?` as well.
