### ISSUE TITLE
Black squares appear in images when zooming

### ISSUE THREAD

**Issue by jpa4ad** [benwbrum/fromthepage#1690]
![DodgeLetterbooks Screenshot](https://user-images.githubusercontent.com/26741637/78685639-061f7400-78c0-11ea-89a6-54ccffd3a308.png)

Transcriber reports black squares appearing in some images when zooming in on the image. See attached screen shot. Transcriber reports it has happened three times, but the error disappears when she backs out of the selected page and returns to it. I have not received reports from other transcribers of this error. 

J. Ambuske

**Comment by saracarl** [comment]
@jpa4ad this is probably caused by delays serving the image tiles from the CONTENTdm image server or -- if no one else is experiencing this -- a slow or spotty network connection (I know mine is these days) that makes the tiles load slowly or time out.  I don't know if there's anything you can do about it, but if you could provide the page link (does it only happen on one page?  one item?) that might help pin it down or let us inform OCLC.  

We can look, but I'm not sure there is anything we'll be able to do.

**Comment by jpa4ad** [comment]
I suspect you are correct, both on the tiling issue and on the spotty network connection. The latter is the more likely culprit here. This seems to be an issue with this particular transcriber. Nevertheless, here is a link to the specific image:

https://fromthepage.com/gwbooks/letter-books-of-harrison-h-dodge/harrison-dodge-letters-october-1885/display/962903
