### ISSUE TITLE
Restrict all transcribed works in a collection

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1742]
Currently, the 'restrict collaborators' feature allows a particular work to be made read-only to the public, but read-write for a set of specified collaborators.  Several institutions would like to use this feature to authorize a restricted set of users to edit after the public (or students) have transcribed, or transcribed and reviewed works.  The challenge is that this requires too much effort for large collections of small documents, since every single work would need to be edited by hand.

Proposal: Add a new "restrict completed works" button to the collection settings, which would locate all unrestricted works within the collection which had pages in `transcribed` or `marked blank` states, and mark them restricted.

See also recent comments on #1178

**Comment by benwbrum** [comment]
@mulcare and @lenathelibrarian Can you weigh in on whether this would be helpful in your work-flows as well?

**Comment by saracarl** [comment]
We should look at this with #866 in mind as well.  I think they attempt to accomplish the same things.  This one doesn't include "needs review" (and perhaps it should?)

**Comment by lenathelibrarian** [comment]
@benwbrum @saracarl Yes! I won't speak for Ross, but I think for us in maps this would be the most elegant solution for the problems in #866 that we see too. We had an issue recently with a user who undid someone else's work on a page that was completely done -- they were trying to be helpful but you know how these things can go -- so to be able to restrict further edits would be absolutely perfect for us. Thanks!

**Comment by mulcare** [comment]
This would be helpful, yes. If this wasn't combined with some of the features discussed in #866, my preference would be for this to _not_ include works marked 'needs review'. This would allow us to leave the 'automatically mark saved works as needs review' feature on, then tell people to just leave things as 'needs review' until an authorized person comes through and unchecks it (thus marking it 'transcribed' and allowing this 'restrict complete works' feature to capture and restrict it).

This is not quite the same thing as an 'incomplete' flag as described in #866, at least to my mind, but it does give a little more control of the status of a work and the ability to edit it.

I can describe this elsewhere if if would be helpful, but here's the setup that allows for the workflow that the team of collection owners I'm working with seem to be looking for:

### Role

- Owner
- Editor*
- Collaborator

### Work Status

- untranscribed
- incomplete*
- blank
- needs review
- transcribed

* New additions

With this organization, collaborators can move a work from untranscribed to incomplete ("I'm working on this, saving my work, but not ready for it to be reviewed by an editor.") to needs review ("I think I'm done with this--there's no lingering questions from me or other collaborators. I'm ready for an editor to take a look."). Editors can move works from any status to transcribed (though in practice would look for works needs review). Owners can do this too, but unlike editors, can add and delete works, etc.

It may be that this doesn't fit with the way you all conceive of the different roles and statuses--totally understandable if so. It does effectively make it impossible for collaborator to get something to transcribed status themselves, which may not be desirable across the entire platform.

My fear with this 'restrict all transcribed works in a collection' is marking something as needs review is the only thing that makes a partially transcribed work not have the transcribed status. Imagine this scenario:

There's a single page work with 10 words on it. I open it, transcribed 2 words, save, and close. As a collaborator I have the ability to decide whether this 'needs review' or not. I haven't received any specific instructions, so I take a guess that I should _not_ flag this for review, as it isn't complete--I'm planning on coming back to it later.

If I'm understanding current behavior correctly, this work is 'transcribed'. Running this new proposed feature would restrict collaborators for this item and any others where this scenario has played out.

**Comment by ThomBurns** [comment]
@mulcare If this feature is coupled with the "All initial transcriptions need review" feature then the scenario you mentioned would not happen. Our collection uses this so every transcription is at least reviewed by two public volunteers. However, I do see the issue you raise if you use the "Needs Review" to flag particularly difficult pages. 

I like the automatic nature of the original proposal. But maybe a checkbox that says "Finish" or "prescribed" would work better since "Needs Review" is used differently by others.

**Comment by ThomBurns** [comment]
A major advantage to this "Restrict all transcribed works" would be that you one could preform advanced formatting and editing while the work remains viewable and readable to the public. We use advanced formatting and HTML mark-ups but do not expect our volunteers to do the advanced coding. So we could have staff add the extra coding in this restricted stage and not confuse volunteers or have someone undo the work that a staff member did. 

Also since we are linking directly to FtP in our online database, it is better for us in the long term to restrict completed works and not have to move them to an inactive collection and thus need to update the URL. The frustrating thing at the moment is that if you have a team of staff members restricting collaborators would require us to add at least four users individually for each work.

**Comment by benwbrum** [comment]
This needs to be branched off of `development` since we want to ship it soon.

**Comment by benwbrum** [comment]
@diegoviola We want to add a new "Restrict Transcribed Works" button to the Collection->Settings page underneath Collection Privacy.

If a user presses this button, we should loop through all of `@collection.works.where(:pct_complete => 100)` and set `restrict_scribes => true`.

**Comment by benwbrum** [comment]
It's possible that this might be faster if we did it in a single Arel statement like `update_all(:restrict_scribes => true` at the end of the where clause.

**Comment by benwbrum** [comment]
This feature has been developed and deployed to FromThePage.com.  It will be included in a release for self-hosted installations later in the week.

@mulcare @lenathelibrarian and @ThomBurns, we'd love to know how it works out for you.  The new button is located on the right side of the collection Settings screen, down towards the bottom.
