### ISSUE TITLE
"Revert" button in work setting's transcription conventions

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1756]
Currently the transcription conventions at the work level have a disabled "revert" button if they match the collection transcription conventions.  That's confusing to folks.  Instead of disabling the button we should hide it.

![image](https://user-images.githubusercontent.com/708566/83770138-53149200-a646-11ea-9cb3-110a03c3dae9.png)

**Comment by benwbrum** [comment]
wrap "Revert transcription conventions to collection default" and the Revert button in a div.  Whatever javascript we have that disables the revert button now should hide the div (rather than disable the button).

**Comment by isabelabarton** [comment]
https://github.com/benwbrum/fromthepage/blob/99d677c78c9b91ecb4ce7ae27ba8023b90d9fcde/app/views/work/edit.html.slim#L81

I think this spot in the code might be saying something about the revert button then the button is disabled, so I could put something instead of "disabled." There could be something called "hidden" or something similar?

**Comment by saracarl** [comment]
Yes, that's the right place.  The best approach would be to not show the revert button at all (in the case where the button is currently disabled).  Ignore what Ben said earlier about javascript -- there is not javascript used to disable the button in this case.

**Comment by isabelabarton** [comment]
Where is this issue specifically present so I know where to check if the code change works or not?
