### ISSUE TITLE
Internationalize Libraries (devise/will_paginate/ago/validation)

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1820]
Currently, messages displayed by libraries are showing up in English.  These include

- [ ] Sign-in screen (devise)
- [ ] Sign-up screen (devise)
- [ ] "_n_ days ago" shown in short deed list
- [ ] "_n_ days ago" shown in full deed list
- [ ] "_n_ days ago" shown recent edits/recent notes for a collection
- [ ] "_n_ days ago" shown on page versions
- [ ] "Last edit over _n_ days ago" shown `display/read_work` next to each page.
- [ ] "Showing 4 records of 10" on most paged views (`display/read_work`,`collection/show`, etc.) (will_paginate)
- [ ] Error message saving a transcript with bad mark-up is in English

These all need to be re-tested with browser locale set to Spanish before we can really verify that they need work.

**Comment by benwbrum** [comment]
Please find out what happens for these messages if you set your browser to Spanish; then apply the language files for the built-in libraries (if available) and extract them (if not).

**Comment by sylvieed** [comment]
### Devise

Devise is currently localized manually by us, and it seems like our locale files for Devise are necessary. When they are removed, Devise translations are only shown in English when the language is switched to Spanish or Portuguese. (Devise initially [only has an English localization](https://github.com/heartcombo/devise/tree/main/config/locales))

Since we've already localized Devise to Spanish and Portuguese, we can just keep those translations in place. Looking forwards to French, Devise has [resources to a lot of localizations](https://github.com/heartcombo/devise/wiki/I18n) and/or there is a [`devise-i18n` gem](https://github.com/tigrish/devise-i18n) that we could pull a French locale from.

### Ago

"_n_ days ago" **is** localized to Spanish and Portuguese. No changes needed.

![spanish ago](https://user-images.githubusercontent.com/35716893/172883150-bd0ebe15-9d6a-47e1-911c-0c18dcf3c219.jpg) ![portuguese ago](https://user-images.githubusercontent.com/35716893/172883688-69dd2145-40e0-4227-8f0a-3f9202c22deb.jpg)

### Will Paginate

![will paginate](https://user-images.githubusercontent.com/35716893/172879461-e6fb556d-02f6-4bf2-b186-0828844a57ef.jpg)

Pagination is only shown in English, no matter what language you prefer. This is because `will_paginate` is only localized to English. The good news is that `will_paginate` [is internationalized](https://github.com/BrumfieldLabs/will_paginate/tree/master/lib/will_paginate/locale), we just need to localize it to Spanish, Portuguese, and in the future, French.

### Errors (ActiveRecord)

Whether or not errors are correctly localized is weirdly inconsistent. A couple of examples:

- With a bad transcription markup, there is no translation other than English.
<img src="https://user-images.githubusercontent.com/35716893/172888025-7a8343da-d4a2-4ab7-997b-8f3cdb6584f4.jpg" width="60%">

- With a work or collection title that's too short, half of the translation is localized.
<img src="https://user-images.githubusercontent.com/35716893/172888023-ca3a1975-0873-42d4-b678-cef5729a4b03.jpg" width="50%">

- With an invalid login, the _other_ half of the translation is localized. I think this is because of our Devise locales.
<img src="https://user-images.githubusercontent.com/35716893/172888024-973a36ea-7b53-4366-bb1b-056d5e24e459.jpg" width="58%">

**Comment by benwbrum** [comment]
There is a chance that the `errors prohibited this...` is something that happens when ActiveRecord tries to save a model and fails to find a (very specific) key in a message catalog for the model.

See the first (or best) answer here: https://stackoverflow.com/questions/20676111/rails-i18n-not-working-for-header-error

**Comment by benwbrum** [comment]
(Note that that would not explain the five places where we are actually using a `...prohibited this...` string literal in the views.)

**Comment by saracarl** [comment]
https://github.com/benwbrum/fromthepage/search?q=error+prohibited

**Comment by saracarl** [comment]
For will_paginate, you'll need to fork the original repo, and then create (via i18n-tasks) message files for spanish, portuguese, and french (with translation); then make our Gemfile point to your fork.

Once we are happy with the messages, you should create a PR back to the original will_paginate gem.
