### ISSUE TITLE
Put transcriber documentation into the help tab

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1832]
Copy the following three articles from the documentation:

Advanced Mark-up

Table Encoding

Encoding mathematical and scientific formula with LaTex

Into the "Help" tab defaults for each project.

**Comment by JosieBrum** [comment]
Should I just copy and paste the text or put in a link to the articles?

**Comment by JosieBrum** [comment]
https://wary-oil.flywheelsites.com/project-owner-documentation/advanced-mark-up/

https://wary-oil.flywheelsites.com/project-owner-documentation/table-encoding/

https://wary-oil.flywheelsites.com/project-owner-documentation/encoding-formula-with-latex/

**Comment by benwbrum** [comment]
I think that putting in a link to the articles is the right thing to do.

You're right that the file you identified (fromthepage/db/migrate/20111227032246_transcribe_help_page_block.rb) is the one that created this text.  The complicated thing about this is that the text itself is stored in the database, and the file you found is the code that put it there (in 2011).  We'll need to create a [new migration](https://guides.rubyonrails.org/v3.2/migrations.html) that starts by deleting the existing page block, then re-creates it with the new text.  This migration will look very similar to the 20111227 one, but will probably have a `change` method instead of the old-fashioned `up` and `down` methods.  You should have `change` start by doing the same deletions in the old `down` method, then do the same creations as in the `up` method.
