### ISSUE TITLE
Autolink should choose most recently linked subject in case of ties.

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1973]
Assume the following
* Page 1 text: `Hello [[John Jones|Mr. Jones]]`
* Page 2 text: `Hello, [[David Jones|Mr. Jones]]`
* Page 3 text: `Goodbye, Mr. Jones`

If a user presses _Autolink_ on Page 3, text `Mr. Jones` should match subjects for both `John Jones` and `David Jones`.  The behavior in this case is undefined, but most certainly matches records in order of database insertion, so that the Page 3 text will be autolinked as `Goodbye, [[John Jones|Mr. Jones]]`.  

We should attempt to re-order the text by most recent occurrence within the work (or in time) so that it is more likely that Autolink will present the correct subject within the narrative.

**Comment by ThomBurns** [comment]
I definitely like having this as the first order of logic. I would just like to say that I would like for the logic to look for the most tagged subject not just for the last time the phrase was used. Using the above 

- Page 5 text: I saw [[John Jones]] again. 

- Page 6 text: [[Mr. Jones]] was not excited to see me.  

I would like Auto Link to assume that Page 6 is referring to John Jones since it was the last referenced on page 5 not to link to David Jones because page 3 was the last time Mr. Jones was tagged.
