### ISSUE TITLE
Require a collection whenever a work is created.

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#201]

**Comment by kolking** [comment]
@saracarl what if we'll add a select box with the list of collections (owned by the current user) to the "create work" modal dialog?

![image](https://cloud.githubusercontent.com/assets/4656448/9264979/4da344b2-4235-11e5-8217-d09daaf32ed2.png)

**Comment by benwbrum** [comment]
Yes, this would be ideal.

**Comment by kolking** [comment]
@benwbrum one more question - should we allow to create work without a collection? Or, collection should be required?

**Comment by benwbrum** [comment]
What I'd really like to do with collections is to have a sort of default
collection for every work-owner or even user account.  (This could be
lazy-created via a find_or_create_default_collection method on the User
model).

When users aren't manually creating collections, how would their fields be
populated?  They would initially have a title "Username's Collection" and
categories for "People" and "Places", and maybe they should also be marked
as private.

So that would get us a collection for users who had not created one.

How should we populate the dropdown when users are creating works?  I
believe that we should provide them with options, but use the most recently
modified collection.  In other words, if a user creates their account, then
imports 3 documents to their original collection and renames it "X", then
six months later they start a new project, I'd like them to create a new
collection "Y" and whenever they upload works, the default should be "Y"
(at least after they add the first work to it).

How does that sound?  (Maybe this should be spun off to another story?)

**Comment by kolking** [comment]
@benwbrum yes, something like a "default" auto-generated collection (when there are no collections created) sounds right for me. But thinking about it more I have a feeling there is no big difference between this approach and creating a work without a collection defined. If we need to display these works, we can easily query them. So what's the reason for auto-creating such "default" collection?

I think that right now we should do the following:
1) Display collection select box for "create work" dialog
2) Allow to create work without a collection - if there are no collection for that user, or he just don't want to include this particular work into any of his collections yet
3) Also add the collection select box in the work settings page, so user will be able to set/change collection in the work section, right now it's only possible in the collection section

What do you think regarding these three points above?

**Comment by kolking** [comment]
I've added collection select box for the New Work modal dialog and also in the Work Settings tab. As I remember there was a feedback about that - the ability to set a collection from the work section, not only from the collection section.

**Comment by benwbrum** [comment]
Yes -- very nice!
