### ISSUE TITLE
Transcribe action should launch fullscreen

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#202]
Feedback from user testing:

We should launch the fullscreen editor by default if possible, rather than requiring users to click on the "Fullscreen" button.

**Comment by kolking** [comment]
I understand that somebody will prefer the fullscreen mode, but I think that making it default is not a good idea for the overall user experience. If we'll make it default, new users will be confused when they open the transcribe page for the fist time. They will see a page without header/footer, without navigation elements. Transcription conventions and user notes will be also hidden.
Switching to the fullscreen mode (and back) made without page reload and it's blazing fast. As for me, it's much more obvious to switch **to** fullscreen mode rather than get to it by default and switch back. I would suggest to leave it like we made now, but sure, it's totally up to you.

**Comment by benwbrum** [comment]
More feedback from user testing:

I think that the default should start without fullscreen, but there should be a toggle so you can set it to automatic fullscreen. then, transcribers who have learned the original interface can choose to eliminate that click.
would this be a good compromise?
me, i'd learn my way round the site (and did in 5mins, more or less) and then stick with fullscreen.

**Comment by kolking** [comment]
![image](https://cloud.githubusercontent.com/assets/4656448/12586308/d3d91d42-c460-11e5-9091-ff8535676add.png)

By default it shows without fullscreen, when a user switch to fullscreen, there is the checkbox shown above, so he can check it and later all transcribe pages will automatically open in fullscreen until user uncheck the checkbox.
I've decided to show the checkbox only when transcribe page opened in fullscreen, it seems more obvious to me.
