### ISSUE TITLE
UI enhancement: abandon subject creation midstream without losing transcription

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2313]
> HI. I've just started tagging subjects in my project, and I've got a question. When I tag a subject, then save the page, if I've created a new subject I am taken to the next page where I put that subject in a category. But sometimes, I get to that page and see that oops, I just spelled it wrong or left out a punctuation so I don't actually want to be creating a new subject But if I hit the back button, I lose all the work I did on that page I was tagging. Is there a way to kind of say "never mind, don't create a new subject for that one" without hitting the back button. Does that question make sense? Thanks

right now here's the only solution I could give them:

- go ahead and create the new subject
- undo/fix the subject link in the transcription
- go to the collection's subject's tab, find the subject, and delete it.  (You may or may not have permission to do that -- I think only collection owners can.)

**Comment by benwbrum** [comment]
We create subjects when a user hits the `Save` button on the transcription screen and `transcription_controller#save` runs.  We then redirect the browser to `assign_categories`, which is a step that lets them categorize newly created subjects if they exist, or skip the step entirely.

I think that the thing to do here is to have the `assign_categories` view present the user with an option that takes them back to editing the page.  This is exactly what we do currently, but [the button](https://github.com/benwbrum/fromthepage/blob/development/app/views/transcribe/assign_categories.html.slim#L27) is labeled something like "Next".  

I don't think it makes sense to satisfy the implementation suggestion that the user left, since it does not quite follow the actual functionality of the product.  However, it does make sense that a user would want to cancel/quit/edit the subject-creating side-effects of their work.  I see these options:
* Modify the wording of the current "Next" button to better indicate that pressing the button will let the user correct mistakes.
* Add a new button (in addition to "Next") which offers the option to continue editing the page, with the same action as the current button.
* Modify the current "Next" button to take the user to transcribing the next page in the document, and add a new button for "Continue Editing" that takes the user back to transcribing the current page.

**Comment by saracarl** [comment]
What about a 'cancel' button that takes them back to editing the page without assigning a category?

**Comment by benwbrum** [comment]
This is something we should consider as part of the save/done and page status work.
