### ISSUE TITLE
Optimize DB queries for collection list

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#248]
Displaying the number of works has slowed down the display of the collection list.  We should investigate either `include` or `counter_cache` when we're displaying that page.

**Comment by tbl73** [comment]
The collection list was included in the other optimizations I did a few months ago.  I still think it's a little slow compared to the rest of our changes, but I haven't been able to find a way around it, because of the way we display collections and document sets together.  @benwbrum , do you think this is still an issue?
