### ISSUE TITLE
Spreadsheet rows re-ordered unexpectedly

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#2555]
MO reports a problem with rows getting scrambled in the ledger interface, most noticeably in this page: https://fromthepage.com/missouristatearchives/missouri-slave-schedules/1850-missouri-slave-census/display/1857432

It looks like some of the bottom rows were moved to the top during this edit: 
https://fromthepage.com/page_version/show?page_version_id=25207643

It seems like this could be caused by:
1) Some re-ordering within the spreadsheet editor, in which a user might be able to drag a group of rows to the top
2) A problem with the way we save rows from the spreadsheet, in which the order is scrambled on a save
3) A problem with the way we load saved rows into the spreadsheet, or
4) Some other culprit.

**Comment by saracarl** [comment]
When I look at this page:  https://fromthepage.com/page_version/show?page_version_id=25210466I notice that at the same time the lines get mixed up, the header for middle name changes.  I have no idea if these are related (and the pattern doesn't hold with the other page with mixed up rows), but it's a lead we should investigate.

I asked Christina:
**I'm curious if you changed the Middle Name header from "Owner Middle Name" to "Middle Name" sometime on May 11th?**

Other progress on this is all 'negative' progress:  

- The problem doesn't happen when the transcriber on the page switches; 
- it isn't always the same transcriber; 
- it isn't at the top of the 2nd page; 
- it does seem to be towards the end of the page (is this relevant?  no clue); 
- you can't rename columns in the spreadsheet widget; 
- you can copy rows but you can't paste them in; 
- you can't drag and drop rows.
 
Those tests lead me to think it's a problem within the software rather than a transcriber usability issue.

**Comment by saracarl** [comment]
Diving into the logs we see the following:

>looks at help
preview -- with just headers, no SS.  13:44:57.68
save (to incomplete) 14:44.18.85 -- headers, spreadsheet data starting at Simpson/Porter/Smith/Stevenson ending with Dow/Dow/Sites/Sites/Sites/Sites/  (think this is correct)
DONE (save to needs review)  14:44.47.29  (still looks correct) thread 19022. request saves at 14:44:52.92
save (save to needs review)  14:44:50  (still correct)  thread 19043  (server sees it, but doesn't save until 14:44:54 -- 4 seconds later  14:44.55.29 request finishes)
save (save to needs review) 14:45:07.41  spreadsheet data starting at Powell/Powell/Powell/Powell ending with Powell/Powell/Powell/Powell   thread 19022

These two:

> DONE (save to needs review)  14:44.47.29  (still looks correct) thread 19022. request saves at 14:44:52.92
save (save to needs review)  14:44:50  (still correct)  thread 19043  (server sees it, but doesn't save until 14:44:54 -- 4 seconds later  14:44.55.29 request finishes)

Indicate a race condition where the first save doesn't finish before the second on commences.

**Comment by benwbrum** [comment]
We can solve this by making our database writes more atomic during the `Page.process_fields` action.  This action currently has the following side effects:
* Populating the `source_text` and `xml_text` fields of the `page` object in memory, for use later during the save or preview blocks
* Updating the table cells for the page in the database by
  * Deleting each `table_cell`, then
  * Inserting a `table_cell` for each non-spreadsheet field and
  * Inserting a `table_cell` for each cell of the spreadsheet field

This second step needs to be substantially refactored, since it is slow, non-atomic (leading to the current issue), and stores data when the user presses "Preview" which cannot be reverted if they never save the page.

To fix this, `Page.process_fields` should make no changes to the DB, but rather create an array of `TableCell`s in memory and return this to `transcribe_controller#save`.  Before `@page.save` is called, we should bulk delete/insert the table cells returned here.

**Comment by benwbrum** [comment]
Performance of [example page](http://localhost:3000/missouristatearchives/missouri-slave-schedules/1850-missouri-slave-census/transcribe/1857177)
### Before refactoring
* Save: 32986.2ms, 2408 sql
* Preview: 31288ms, 2390 sql
* Edit post-preview: 

### After refactoring 

#### Pass 1
* Save: 863ms, 47sql
* Preview: 10881ms, 1207sql
* Edit: 12050ms, 40ish sql

#### Pass 2
* Save: 889ms, 47sql
* Preview: 2675ms, 35sql
* Edit post-preview: 1412ms, 38sql
