### ISSUE TITLE
Renaming subjects creates duplicates

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#259]
Renaming "Jeremiah Hunt Grave" to "Jeremiah Hunt Graves" created a duplicate record with no mentions.

**Comment by tbl73** [comment]
Just to clarify, did you rename the subject (in the settings tab)?  When I try that, it created a new record in the articles table that appeared to have all the data from the original record.  (It did not delete the old record; I don't know if that's something that ought to be happening.)  I just want to make sure what I'm supposed to be looking at with this one.

**Comment by benwbrum** [comment]
Hm.  Renaming the subject (by editing title the settings tab) should result
in
* a subject with the new name in the `articles` table,
* all existing `page_article_links` pointing to the renamed subject (with
the renamed `article_id`),
* all page transcripts using the new name within their link text (so
mouseovers work), and
* no record in `articles` with the old subject title.

I think the way I implemented this was to copy the record to a new record
in `articles` with the renamed name, walk through all pages pointing to it
(updating their transcripts), then delete the old record with the old
name.  I'm guessing this algorithm fails sometime before the deletion,
which is why we're getting this junk in the DB.  I'm absolutely open to new
algorithms, especially involving a rename-in-place.

**Comment by tbl73** [comment]
I've been looking into this again, and I don't know what I did the first time. This seems to be working correctly, as best I can tell.  If I rename a subject, it appears to be renamed in place in the database - it keeps the same id, with a different title.   There are still references etc, because it's the same record/article_id.  Obviously the actual text on a page isn't changing, but the link text does, so mouseovers work.  Can you check and see if it's working as you'd expect?

**Comment by tbl73** [comment]
In looking at something else with autolinking, possibly the page_article_links display text needs to be updated?

**Comment by saracarl** [comment]
@benwbrum please review
