### ISSUE TITLE
ampersands in find a project page not escaped

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2939]
Ampersands in the Find A Project page aren't escaped, i.e.:

![image](https://user-images.githubusercontent.com/708566/149850157-f731cc38-1a02-4634-86e2-f2eda2daae09.png)

But the same description is on the collection homepage:

![image](https://user-images.githubusercontent.com/708566/149850267-10014301-3645-47e2-b2d4-b4409beef773.png)

**Comment by sylvieed** [comment]
The [Collection homepage](https://fromthepage.com/tngenewhiz/tennessee-legislative-petitions), where the & aren't escaped, [corresponds to](https://github.com/benwbrum/fromthepage/blob/main/config/routes.rb#L65) the [`collection#show` ](https://github.com/benwbrum/fromthepage/blob/main/app/controllers/collection_controller.rb#L129-L197) action. The [view for the page](https://github.com/benwbrum/fromthepage/blob/main/app/views/collection/show.html.slim#L10-L11) shows 
```
@collection.intro_block
```

The [Find A Project page](https://fromthepage.com/findaproject), where the & are incorrectly escaped, [corresponds to](https://github.com/benwbrum/fromthepage/blob/main/config/routes.rb#L316) the [`dashboard#landing_page`](https://github.com/benwbrum/fromthepage/blob/main/app/controllers/dashboard_controller.rb#L141-L160) action. The view for the page has a [`snippet` variable](https://github.com/benwbrum/fromthepage/blob/main/app/views/dashboard/landing_page.html.slim#L12) representing the paragraph where the issue lies, and [it is set as](https://github.com/benwbrum/fromthepage/blob/main/app/views/dashboard/landing_page.html.slim#L6) 
```
-snippet = truncate(strip_tags(c.intro_block), length: 300, separator: ' ') || ''
```


Both of these reference a collection's `intro_block` property, but the one with the issue also calls `strip_tags` on it. As [this issue](https://github.com/rails/rails/issues/28060) and [this site](https://www.rubydoc.info/github/flavorjones/loofah/Loofah/TextBehavior) explain, `strip_tags` is escaping special characters such as &.

### Possible solutions:

1. Replace `strip_tags(c.intro_block)` with `Loofah.fragment(c.intro_block).text(encode_special_chars: false)`
2. Unescape the characters after `strip_tags` escapes them. Use an unescaping method such as `CGI.unescapeHTML(strip_tags(c.intro_block))` or `URI.unescape(strip_tags(c.intro_block))` 

Both of these solutions change [line 6 of landing_page.html.slim](https://github.com/benwbrum/fromthepage/blob/main/app/views/dashboard/landing_page.html.slim#L6).

**Comment by benwbrum** [comment]
I think that we might run into problems using `truncate` on unescaped HTML tags, since `truncate('some text <b> many more characters</b>', length: 20)` would result in an unclosed `<b>` tag, bolding everything else on the page.  The same might happen with 2, assuming that we kept truncate.  

Let's try the Loofah.fragment approach.
