### ISSUE TITLE
mismatched spreadsheet cell types "red"

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3001]
Dates or numbers in spreadsheet transcription that don't match what is expected by hands on table have a red background applied.  This is off putting to transcribers, who are probably encountering a real anomaly in the text they are transcribing.

Let's make it yellow.

**Comment by benwbrum** [comment]
This will require overriding the stylesheets we import from HandsOnTable.

**Comment by benwbrum** [comment]
There are two problems with the current HandsOnTable validation:
* Cells with data which does not conform (i.e. non-numeric data in numeric cells) are displayed as red, rather than orange or yellow
* Cells are colored only when the data has been entered by a user and not saved.  If a user edits a form with non-compliant data, we do not color the relevant cells.

We'd like to address both of these.

**Comment by atbah** [comment]
@benwbrum  To fix this issue,  please follow the below steps. 
Go to this file => [app/views/shared/_handsontable.html.erb](https://github.com/benwbrum/fromthepage/blob/development/app/views/shared/_handsontable.html.erb), and add these code

```
<style>
  .handsontable td.htInvalid {
    background-color: yellow !important;
  }
</style>
```
![image](https://github.com/benwbrum/fromthepage/assets/159004143/5e5da270-455c-4390-be98-d7d05cc06c3b)

`  // validation for initial data
  hot.validateCells((valid) => {})`
  
![image](https://github.com/benwbrum/fromthepage/assets/159004143/84107164-9f07-4f23-a5e2-d948d1f2ec54)
