### ISSUE TITLE
Tagged project view for "Find a Project"

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3051]
We're adding the ability to "tag" projects with a vetted set of tags to make it easier for transcribers to find material they are interested in.  

We'd like to add a partial view that for now we'll put at the top of the "Find a Project" view that shows those tags.  When you click on a tag, you get a list of collections (similar to the list on the Find a Project view) that have been tagged with that tag.

**Comment by saracarl** [comment]
See #3043 for the data for the initial data for this.

**Comment by saracarl** [comment]
For now, we're going to mock this data up in a separate branch for Nick to work on the UI.

**Comment by benwbrum** [comment]
We've created a new branch with a `newlandingpage` view and some (static) sample data in [this branch](https://github.com/benwbrum/fromthepage/compare/3051-tag-cloud-find-a-project)

We'd like to take that and make it an attractive, easy-to-use way for users to find projects by keyword.

* The list of keywords should be displayed as an attractive tag cloud (rather than the font-size prototype I put together)
* Clicking a keyword should display the list of collections to the user.  This could be in a modal pop-up, on a separate page, in a pane below, or anything else that looks good and makes sense.

**Comment by benwbrum** [comment]
You should be able to access the new view via http://localhost:3000/newfindaproject

**Comment by kolking** [comment]
I've added styles for the tag cloud, now it looks like this on the test data:

![image](https://user-images.githubusercontent.com/4656448/164944063-3ff8798c-a300-4bde-bf5b-e88f2fab0a4e.png)

I believe that clicking a tag should either open a new page, or show the list below (in case the list won't we long), so I've wrapped individual tags with `<a>` where you can add a `href` attribute.

A few notes regarding the `data-weight`. This attribute used to set size for a tag. Right now it uses `collection_list.size` value, but ideally we need to use a value in `0...9` range. Therefore it's better not to use the `collection_list.size` as is because there will be no visual difference between a tag with the size = 9, and a tag with the size = 39. It would be better to calculate a value in `0...9` range based on the `collection_list.size` interpolation among all tags.

For example, we have 10 tags, where the minimum `collection_list.size` is 3, and the maximum `collection_list.size` is 15. Then, a tag with `collection_list.size = 3` should receive `data-weight = 0`, a tag with `collection_list.size = 15` should receive `data-weight = 9`, and so on.
