### ISSUE TITLE
html in find a project carousel

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3146]
Collection descriptions with a lot of HTML look bad on the find a project carousel:
![image](https://user-images.githubusercontent.com/708566/167487568-4e935125-9483-40c3-98f8-a2dc5d169004.png)

Are truncated and look fine here:  https://fromthepage.com/vrprinceton

You can see the results of the html here:
https://fromthepage.com/vrprinceton/butler-field-books

I think if we change the carousel to show the same description that shows up on the owner page we'd be good.

**Comment by sylvieed** [comment]
This is how the description is displayed on the account page when it's correctly truncated.

https://github.com/benwbrum/fromthepage/blob/f679cdd74ed3ecd5612018a25ebb51cef1c9d4f4/app/views/dashboard/_hierarchical_collections_and_document_sets.html.slim#L3

This is how the description is displayed on the Find a Project page when the HTML is shown.

https://github.com/benwbrum/fromthepage/blob/f679cdd74ed3ecd5612018a25ebb51cef1c9d4f4/app/views/dashboard/landing_page.html.slim#L50

It looks like we changed `strip_tags` to `Loofah.fragment` for https://github.com/benwbrum/fromthepage/issues/2939 so that ampersands wouldn't look like `&amp;` (because `strip_tags` [escapes special characters](https://github.com/rails/rails/issues/28060)). But it seems like `Loofah.fragment` doesn't actually behave the same way `strip_tags` does and that's why all of this HTML is showing.

**Comment by benwbrum** [comment]
The problem appears to be the `style` element in Princeton's intro_block.  We can use Nokogiri to remove this, as we do here: https://github.com/benwbrum/fromthepage/blob/f679cdd74ed3ecd5612018a25ebb51cef1c9d4f4/lib/search_translator.rb#L50
