### ISSUE TITLE
UT: Already existing work cannot be moved into a collection

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#338]
Already existing work cannot be moved into a collection at the moment. Permissions issue? Check Ece’s Terrels’ Note on Greek NT in HRC file

**Comment by saracarl** [comment]
More stuff I suspect is related to owners and permissions:

Ece can’t create a collection at this time
Ece can’t transcribe “brother_p1” (under Terrell, Calvert and Troy) still. “You are already signed in”.

**Comment by atomrab** [comment]
The second of those issues is because I had restricted the editors for that letter, and I hadn't added Ece. I've added her now, so she should be able to transcribe. I also tested, with a test account, the action that happens when you click on the "transcribe" tab of a work for which you are not an authorized editor, and this is it -- you are sent back to the editor dashboard (watchlist tab), and a yellow banner message appears that reads "You are already signed in". 

So the behavior is right (non-owner of work not permitted to transcribe), but the message and redirect are very confusing (better would be a banner or popup on "transcribe" tab click reading "You do not have permission to transcribe this work").

**Comment by benwbrum** [comment]
Addressing the original problem, we need to revise the way works are moved from one collection to another.  Previously, the collection settings listed works the owner had uploaded and allowed them to add them to the collection, while also listing works in the collection and allowing them to remove them from the collection.  This may have been obliterated when we addressed deleting things.

**Comment by tbl73** [comment]
I just checked, and currently if you remove a work, the collection ID is
set to nil and you lose access to it.  It doesn't get deleted, though.  It
looks like something isn't right with the code that returns the list of
owner_works for the user (which is what that list is based off of), so that
may be a place to look first.

**Comment by saracarl** [comment]
We're going to close this -- we don't allow orphan works anymore, and you can move a work in it's settings.  

@atomrab if you disagree, feel free to reopen and we can discuss more.
