### ISSUE TITLE
login as transcriber

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3415]
Add a guest login to the admin dashboard in the transcriber view.  Copy it from the owner view.

**Comment by ajistrying** [comment]
I'll take a crack at this one.

**Comment by saracarl** [comment]
@ajistrying if you send me your email address I can share a pruned database with a lot of data with you.  sara@fromthepage.com

**Comment by ajistrying** [comment]
@saracarl That'd be great, my email is wjohnson@eleudev.com, thank you!

**Comment by ajistrying** [comment]
Hoping I can still get that pruned db when you get a chance, looking to tackle another issue in the meantime 👍

**Comment by ajistrying** [comment]
@saracarl I was able to get the dmp file and get it into the db, but I believe that data might not be as up to date as the shape of the database currently stands today. When I use that dmp file and query the users table for example, some fields seem to be missing (`undefined method` errors being thrown within the console). Like for instance when signing up a fresh account, the app gets snagged on an initial check for the `preferred_locale` field on the user model. The `preferred_locale` field wont be available on the model from the data of that dmp since its from 08-20-2020, but the addition of the `preferred_locale` field was added later that year on 11-28-2020.

Totally get that you'd need to give me an older more pruned down version of the db, but any help on addressing this would be awesome, thanks!

**Comment by benwbrum** [comment]
Have you tried doing a `rake db:migrate` yet?

**Comment by ajistrying** [comment]
@benwbrum I did, I'll caveat all of this by saying that I'm running the app within a docker container. 

The steps I took within the container were:
1. Run `rake db:migrate`
2. At this point all migrations are up and good to go
3. Load in the .dmp file via `docker exec -i [container_name] mysql -ufromthepage -pfromthepage diary_development < path/to/dmpfile`
4. When I run `bundle exec rails db:migrate:status` I see that some migrations have been rolled back, while some are still up, so I believe utilizing this particular dmp file may be rolling some migrations back, but I'm not 100% sure

Of course I'm down for any other way to do this, developing with docker might not be the best way to go here! Thanks

**Comment by benwbrum** [comment]
Ah!  I see the problem.

The mysql dump file--if you look inside it--is a series of commands that drops all the tables from the original DB, then recreates them, then loads the data.  Running it after a db:migrate will leave you with inconsistent data -- you'll have old versions of all the tables we knew about when the dump was made, and new versions of any tables that we didn't know about. 

Try doing step 3, followed by step 1.  Let us know if you hit any errors doing the migrations.

**Comment by benwbrum** [comment]
I'm working on preparing a fresh copy of the pruned DB now.  Stay tuned!

**Comment by ajistrying** [comment]
Awesome! Sara shared a specific link to the 2020 dmp file, but I believe I'll need a new link to the newer file or to the drive directory where the file is held.

Thank you both for the help in getting me setup to help continue contributing 🙏

**Comment by saracarl** [comment]
@ajistrying just shared a new db with you.

**Comment by saracarl** [comment]
merged and deployed!  Closing.
