### ISSUE TITLE
[FTP UT Library install]: owner dashboard does not show existing collections or works

### ISSUE THREAD

**Issue by atomrab** [benwbrum/fromthepage#344]
The owner dashboard allows you to upload new material, and it's clearer that you need to create a collection first (and how you do that). But the tab labeled "Your works" tells me that I don't have any collections (but there are three counted above) and doesn't say anything about works. This would be an excellent place to list both collections and documents, with some quick-add tools to put a document from the list into a collection. As it is, it's a little confusing.

![image](https://cloud.githubusercontent.com/assets/4740995/16696513/db4c20c6-450a-11e6-8e6d-6ba9be220a8f.png)

**Comment by benwbrum** [comment]
I suspect that this is a bug, due to the amibiguity between the owner list on `Collection` and `User` represented as a many-to-many relationship (when an owner adds owners to a collection) and a many-to-one relationship (when an owner creates a collection).  We have named scope finders to support that, but just aren't using them, it seems.

A meta-story to tackle here is to rename `collections.owner_user_id` to `collections.created_by_user_id`, add an `after_create` filter on `Collection` that adds the current user to the list of collection owners.  Then we can blowtorch out any code that  uses the old, bad, inconsistent associations using the foreign key and maybe this problem will quit biting us in the butt every two months.

**Comment by benwbrum** [comment]
Note that we'll need to create a migration script that also migrates the data, populating the `collections_owners` table from `collections.owner_user_id` where necessary.

**Comment by tbl73** [comment]
@atomrab - I'm having trouble replicating this issue - are you still seeing this problem?

**Comment by atomrab** [comment]
Though while I'm thinking about it, it would still be useful to be able to get to a list of just collections (currently I have to scroll a lot) and to see how many documents I own and/or have been added to as an owner (right now I only see 31, but I'm a de facto owner of nearly 80). Also, linking the numbers at the top to the things mentioned (image sets, notes) would be helpful, too. I think I know where my notes are, but I have no idea which image sets I own (maybe uploads I did myself?).

**Comment by saracarl** [comment]
We're going to close this one out.  

Issue #274 covers the "linking the numbers at the top to the things mentioned" -- it's still in progress.  

We're getting rid of the concept of Image Sets -- see issue #356 -- it's an old concept around uploads we really aren't using anymore.

I suspect this bit is still a bug:
"how many documents I own and/or have been added to as an owner (right now I only see 31, but I'm a de facto owner of nearly 80). "  (If you didn't create the work, but are an owner of it, it may not show up in this list.).  
I opened #412 for that one.
