### ISSUE TITLE
Account/user wide footer setting

### ISSUE THREAD

**Issue by anabeabas** [benwbrum/fromthepage#3468]
Add a feature that lets project owners put the same footer across all collections.

**Comment by benwbrum** [comment]
There are a handful of attributes which are stored on the `Collection` model that we have learned should be identical across all of a user's collections.  The `footer` is displayed at the bottom of each page on a user's projects, and is used almost exclusively for account branding and links to the institution.  Project owners would prefer to configure this once, in their profile, instead of needing to copy-and-paste the same HTML into the `footer` attribute for each collection.

We should move `footer` from `Collection` to `User`, make it editable (for project owners only) in the profile, migrate data to copy the `footer` contents from one of their collections (ideally the one with the longest `footer` contents) into this new field on `User.footer`, then display that in the application layout instead of displaying the collection footer.

**Comment by symmetrically** [comment]
@benwbrum 
What I understand is that currently there is an attribute named footer_block in the Collection Modal which is used to display the footer for that collection(see Image below).  Now, I have to create a new attribute in the User Modal (let's say named footer_block) and copy the longest footer_block from the collections of that user and assign it to the newly created attribute in the User Modal. Then use that footer_block from the user Model, right?

![Screenshot from 2023-03-27 20-19-22](https://user-images.githubusercontent.com/829262/227991514-a9e08351-43a6-46f3-987c-2eadf20a4bb6.png)

**Comment by symmetrically** [comment]
@benwbrum 
As per the requirement, I have added a new attribute in the user modal and moved the `footer_block` logic in the application layout. The question is should I remove the `footer_block` Column from the Collection Modal and the respective files?

**Comment by benwbrum** [comment]
Yes, please remove `footer_block` from `Collection` -- for this attribute we want everything driven by the value in `User`.
