### ISSUE TITLE
pop out image viewer

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3476]
Aaron at NBU would like to pop out the image viewer and put it on a 2nd screen.  

We didn't commit to this, but we should talk to Rainer and see if he could do it.

**Comment by benwbrum** [comment]
A more detailed problem description:

Currently, for simple documents, users are able to read the writing on an image within the OSD/Annotorious viewer on one side of the browser, and are able to type into the editor on the other side of the browser window.  When the user saves their work and navigates to the next page, synchronizing the image and the page being transcribed is trivial, since the server-side rendering loads a new tilesource into OSD to match the page.

For more complex documents like ledgers, the image viewer may be too small.  Users with multiple monitors report that they often download an image from FromThePage, open it in an image viewer (or editor), and read from it in a separate monitor while they type into the FromThePage editor, ignoring the OSD view.  Some users have requested that we add this kind of capability into FromThePage; popping the image viewer out into a separate window for a separate monitor.

We have not addressed this for two reasons:
* Neither Sara nor I work on machines with multiple monitors, so we have no way to test this.
* We are worried about opening a new, separate window with an independent image viewer, because we would need to synchronize both windows when users save their work and advance to different pages.

There is a fullscreen option in OSD, which might be helpful.

**Comment by benwbrum** [comment]
This has been fixed.
