### ISSUE TITLE
CodeMirror support for RTL languages

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#3534]
FromThePage should support transcribing text in any script, but not all features work well for RTL projects (currently Arabic and Urdu).

When we implemented CodeMirror as our advanced editor, we ran into some configuration problems with RTL support.  (Codemirror documentation says that it supports RTL scripts, but we had difficulties when we tried.)  As a result, we took the [shortcut of disabling Codemirror for RTL scripts](https://github.com/benwbrum/fromthepage/blob/66c67e78f30ec7960428743743a2a635f18ac3f1/app/views/transcribe/display_page.html.slim#L106-L108).  In the last two months, one user has complained that the syntax highlighting and auto-complete functionality is not available for Arabic, so this decision is affecting users.

We should do the following:
* Remove the RTL test in `app/views/transcribe/display_page`
* Fix any bugs for Arabic or Urdu users -- change the "text language" in the Settings tab for a work to a RTL language, then test transcribing and editing a document in that script.  Watch for justification as well as odd behavior.
* Add editor buttons to the project (Collection->Settings->Configure Buttons) then try to add XML mark-up to text.  Watch for strange behavior on the cursor and other things that "feel wrong" to someone used to editing HTML+RTL text.

**Comment by symmetrically** [comment]
@benwbrum From the description what i understand is that if i remove the given [check](https://github.com/benwbrum/fromthepage/blob/66c67e78f30ec7960428743743a2a635f18ac3f1/app/views/transcribe/display_page.html.slim#L106) then code-mirror functionality will work for rtl too. But the issue is that for the transcribe tab the cursor direction is on the left side instead of the right side of the editor.
Let me know if I understand the problem correctly?

![Screenshot from 2023-03-20 23-26-02](https://user-images.githubusercontent.com/829262/226594731-188e3790-0b4b-46c1-8783-7a47eb9fd5b1.png)

**Comment by benwbrum** [comment]
I see two problems here -- the cursor starts on the left side instead of the right (as you point out), and also the text is justified against the left side instead of the right.
