### ISSUE TITLE
Henrico County document set notes "More" never returns

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#3537]
Apparently there is a 100% error rate for https://www.fromthepage.com/deed/notes/virginia-untold-bills-of-sale-and-deeds-henrico-county.  If we try to run it, we get the notes feed for the entire site, not just Henrico County 's bills of sale and deeds.

The link might be a to private document set.  By comparison, this works fine: https://fromthepage.com/deed/notes/virginia-untold-bills-of-sale-and-deeds-set

Open questions

- What's happening when we hit the URL?
- What is linking to this URL?

**Comment by saracarl** [comment]
So there's not a collection or document set called 
![image](https://user-images.githubusercontent.com/708566/224778419-a4b478e0-b997-43eb-bc45-7ab604b61055.png)

The collection slug is `virginia-untold-bills-of-sale-and-deeds-set`
https://fromthepage.com/lva/virginia-untold-bills-of-sale-and-deeds-set

So I suspect this *was* a document set, but isn't any more.  We should handle the scenario better (give an error?  or a faster redirect?), but it's probably a crawler rather than a person.

**Comment by benwbrum** [comment]
Closing as wontfix
