### ISSUE TITLE
Image sets

### ISSUE THREAD

**Issue by tbl73** [benwbrum/fromthepage#356]
Should probably retire the relevant controllers, views, and models
legacy feature, no in use anymore

**Comment by benwbrum** [comment]
Agreed.  The only caveat is that we need to make sure that deleting image set records doesn't delete the image files in directories they tracked when those image files are in use for page images.  (I think there may be some filesystem deletion code in the `destroy` methods/callbacks of the `ImageSet`model.

**Comment by saracarl** [comment]
Okay, here's a list of everything I found that *I think* needs to be removed to retire image_sets.  It's a pretty long list.  Basically I searched for image_sets and titled_images in the code and kind of went from there, trying to cross reference the code I found to other code to see if it was doing other things.  They aren't necessarily in a particular order.  As far as I could tell, all of these things are only accessed by image_set related code, but truthfully I can't tell for sure.  I'm still not entirely sure about the flow of some of the image processing/uploading/importing in particular. (As a side note, I wouldn't mind a quick description of how that process actually works at some point.)  I have tested uploading files and importing from archive.org after all these things were done, and it seems to work, so that's at least a good sign.

1. Deleted app/views/transform (includes multiple views).

2. Deleted app/views/collation (includes multiple views).

3. Delete app/views/staging.

4. Delete "get dashboard/staging" line in config/routes.

5. Delete dashboard controller - owner dashboard - def staging.

6. Delete app/views/title.

7. Delete app/views/image_set.

8. Delete collation controller.

9.  Delete transform controller.

10. Delete line 52-58 in the application controller (loading image sets and titled images from params).

11. Delete lib/tasks/image_set_processor.rake.

12. Delete lib/workers/image_transformer_worker.

13. Delete app/controllers/image_set_controller (this includes some deletion code that could maybe trigger callbacks?)

14. Delete app/controllers/titled_image_controller (ditto).

15. Delete app/models/image_set. (I don't see any obvious deletion code in this.)

16. Delete app/models/titled_image. (Ditto)

17. Delete line 21 in app/controllers/admin_controller (def index).

18. Delete line 26 in app/controllers/dashboard_controller (def get data).

19. Delete line 161 in app/assets/stylesheets/application.scss (@import sections/imageset.scss)

20. Delete app/assets/stylesheets/sections/imageset.scss.

21.  Delete line 169-191 in app/assets/stylesheets/dashboard.scss (imageset-related scss)

22.Delete line 18 in app/models/user - "has_many image_sets".

23. Create conditional migration to drop image_sets and titled_images tables from database if they exist.

24. Comment out (?) code in multiple migration files so that those tables aren't created in the first place:
    db/migrate/001_create_image_sets.rb
    db/migrate/002_create_titled_images.rb
    db/migrate/003_add_orientation_to_image_set.rb
    db/migrate/004_titled_image_locking.rb
    db/migrate/20110330024328_image_sets_have_status.rb
    db/migrate/20110705191241_add_pid_to_image_sets.rb

    lines 28, 46, 86, 104 in db/migrate/027_add_indexes_to_everything.rb

25. Testing related:
    Delete spec/factories/image_sets
    Delete spec/factories/titled_image
    Delete spec/models/image_set
    Delete spec/models/titled_image
    Delete line 16 of spec/models/user_spec

    Delete test/functional/image_set_controller
    Delete test/functional/title_controller (?not totally positive on this one)
    Delete test/unit/image_set_test
    Delete test/unit/titled_image_test

Like I said, it's a long list!  Let me know if you see things that shouldn't be deleted.

**Comment by tbl73** [comment]
@benwbrum - any thoughts on this?

**Comment by saracarl** [comment]
Yes delete them all.  This is ready to go!

**Comment by tbl73** [comment]
Note that the migrations and the image_transformer_worker code have been commented out, rather than the files being deleted.  We may want to consider deleting them at some point (although I realize migrations keep something of a historical record).
