### ISSUE TITLE
Item metadata appears in the background of page images

### ISSUE THREAD

**Issue by anabeabas** [benwbrum/fromthepage#3567]
Erin Wilson of Ohio University Libraries emailed us to report a minor display bug. When viewing page images, the item metadata appears in the background and reacts to page scrolling. Oddly, She said she thinks this only occurs the first time the page image is opened in the metadata tab. She linked [this page](https://fromthepage.com/act-one-dancers-with-band-slide-05-murray-louis-circa-1987/nikolais-louis-dance-collection/act-one-dancers-with-band-slide-05-murray-louis-circa-1987/describe) as an example.

**Comment by benwbrum** [comment]
We suspect that the problem is caused by this:

We have three different `div`s displaying the Open Seadragon image viewer, the OCR/transcript text, and the item metadata.  Users should only see one div at a time, and when the "Show Original..." menu is clicked we toggle the display on the div the user choses and hide the other two.

When the page is loaded initially, it looks like we are not hiding the metadata (and text?) divs, but are relying on the images to cover them up.  We should hide them instead when the page loads.
