### ISSUE TITLE
500 Internal Server Error on CS Peirce Collection

### ISSUE THREAD

**Issue by tbl73** [benwbrum/fromthepage#383]
When I click on the "0" pages in each work of the CS Peirce collection on the production server, I get a 500 Internal Server error.  The other pages seem to render fine.

**Comment by saracarl** [comment]
What we need to do for this is tail the log file when the problem is reproduced and get a stack trace of the issue.  @tbl73 we've given you admin rights on the production server, let's talk about this on Monday and I'll show you how.

**Comment by benwbrum** [comment]
@tbl73, I've made you an admin on the FromThePage production site, so you should be able to go to the Admin Dashboard and look at the Tail Logfile tab to see the logs when this happens.  (Note that you want production.log rather than development.log -- in fact, we should probably put that at the top...)

**Comment by tbl73** [comment]
Here's the error message that comes up:
![500_error](https://cloud.githubusercontent.com/assets/16854029/18837080/7a0acc18-83d0-11e6-9b83-8f955e264eba.PNG)

**Comment by tbl73** [comment]
I pushed up a fix in tbl73-dev branch.
I think part of the trouble was that the first pages of the logic notebooks are numbered 0 (and have a position of 0).  The navigation arrows look a little weird to me, because they use the position number, so it says the first page is "Page 0 of 16" (for example), but that is how they're numbered.
