### ISSUE TITLE
Contributions API does not retrieve works modified through subject renaming

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#3895]
When an editor renames a subject, all pages mentioning the subject are updated.  However, we don't log `page_edit` deeds when this happens, since the editor may have modified hundreds of pages and a page edit is a bit more extensive than that.

Jon Fackrell at the Wilford Woodruff Papers points out that these modified works are not appearing in the contributions API, which is fed by `deeds`.  We should make sure that these modifications do appear; probably by doing a `UNION` with `pages.modified_at`.

**Comment by saracarl** [comment]
Discussed with @benwbrum.  We're going to add an `updated_at` column to the page table, which ActiveRecord automatically updates if present.  The migration that adds that column should also copy the latest deed timestamp into that field for each page.  

The contributions API will need to be updated to use page.updated_at instead of deeds.
