### ISSUE TITLE
Jekyll as content manager:  Spike Investigation

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#398]
Similar to the Refinery investigation -- same questions.

**Comment by tbl73** [comment]
Jekyll has  a number of dependencies - when you install the jekyll gem, it includes forwardable-extended, pathutil, ffi, rb-inotify, rb-fsevent, listen, jekyll-watch, jekyll-sass-converter, rouge, colorator, safe-yaml, mercenary, kramdown, and liquid.  There don't seem to be conflicts between any of these and our current gemset, though.

**Comment by saracarl** [comment]
Good to know there aren't any conflicts.  Let's keep going forward with
this investigation, as "adding more gems" is not as risky as potentially
"upgrading gems we depend on at other levels".

**Comment by tbl73** [comment]
Definitely!

**Comment by tbl73** [comment]
Installation was pretty straightforward - as mentioned, there are a number of dependencies, but nothing that conflicts with what we already have.

Static blog posts don't really interact with the user model.  It doesn't allow for comments on posts in itself,  which is something to think about.  It seems like the majority of people who use Jekyll farm their comments out to Disqus or something similar.

It actually might be possible to set it up to do user subdomains in some fashion, anyway - I think you'd have to have multiple Jekyll sites set up, so it kind of clutters up the code, but it does seem like it might be possible.

The other big issue is look and feel - Jekyll uses templates (and there are a bunch out there) which are written using Liquid, so if we want it to look the same as the rest of the site, we might need to learn that.  (There is a gem that converts slim for Jekyll, but it looks like it was abandoned a couple of years ago.)   Also, there is a plugin that should allow it to use the Rails asset pipeline, but right now installing it seems to break the rest of the site.  I *think* that means that it can't point at the css/image files we already have, but I'm still looking at that.

Another potential option along the same lines is Middleman - it seems to be very similar to Jekyll, but it uses ERB rather than Liquid, so it might be easier than adding another templating language to the current setup.  I haven't investigated it much yet, but it seems to be the other major static site generator around.

**Comment by saracarl** [comment]
Nice Analysis.

I wonder how easy it is to use a mix of erb and slim and liquid -- I don't
want to invest in converting everything we already have to liquid, but it's
probably worth it to have someone (possibly @kolking) develop a liquid
template that matches the existing look and feel.

Does Middleman use markdown?

**Comment by tbl73** [comment]
Yes, Middleman does use markdown.  Depending on the type of markdown you prefer, it might require different gems, but it does use it.  It looks like it might support slim, too, which would be nice if it worked.  Do you want me to try and set it up and see how the install goes?

**Comment by tbl73** [comment]
Jekyll or Middle are both options - will decide between them and go from there.
