### ISSUE TITLE
Discrepancy between owner's collaborator time and volunteer's time

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#4002]
> I am the transcription coordinator for the Sandy Spring Museum. We use From the Page for our transcription program and I was wondering if you could help us with a discrepancy we recently discovered.  We are currently in the middle of a project where we are paying some of our transcribers to transcribe material related to the Sandy Spring African-American community. To pay our transcribers, we use the time tracking in the collaborators section of our collection to keep track of their hours. However, one of our transcribers recently informed us that our recorded hours and her recorded hours on From the Page were different. On our end, it said she did 23 hours worth of transcription during the month of February. However, she shared a screenshot of From the Page where it states she contributed 36 hours to the collection (I've attached the image to this email). Is there a reason why From the Page would tell us two different amounts for the same collection during the same amount of time? Please let us know if you need any more information and thank you for your help! 

> Thank you very much for looking into this. After checking, it does not appear this transcriber worked substantially more on the day before or after the beginning and end of February. The transcriber's username is EIM_JMacklin and From the Page states she worked on our collection "Black History in Sandy Spring" for 1398 minutes from February 1st-29th. Please let me know if you need anything else and thank you again for all your help!

**Comment by benwbrum** [comment]
The discrepancy is due to the difference in the two queries used to show minutes to the end user and the project owner.

The end user sees the AhoyActivitySummary for all of their time across any collection.
The owner sees the AhoyActivitySummary for all of their collections and users.

Some AhoyActivitySummary records do not have a `collection_id`, and as a result are not shown to the project owner.

In this user's case, these `collection_id=nil` summaries come from these controller actions:
Ahoy::Event.where(user_id: 32019007, time:[Date.new(2024,2,1)..Date.new(2024,2,29)], properties:{}).pluck(:name).tally
 => {"dashboard#dashboard_role"=>68, "dashboard#landing_page"=>1, "dashboard#watchlist"=>72, "dashboard#your_hours"=>90, "search_attempt#click"=>18, "sessions#create"=>1, "static#landing_page"=>3, "user#profile"=>3} 
2.7.3 :032 >
