### ISSUE TITLE
fix voice dictation option

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#4003]
~~just remove this feature in general and delete all the code associated with it.~~

_see comment below_

**Comment by benwbrum** [comment]
First, we created a voice dictation option, using a Chrome feature to let users dictate into the transcription field.  Then we replaced the transcription field's `textarea` with CodeMirror, a JS library that's a lot more sophisticated.

The problem is that the voice dictation code still writes to the textarea that CodeMirror also writes to, and the two do not remain in sync.  As a temporary expedient, we disabled CodeMirror for projects that had voice dictation enabled.

We've had three requests for voice dictation this month, so we should really revisit this.

If possible, we should get voice dictation working again for projects using CodeMirror.
