### ISSUE TITLE
Add formula bar at the top of spreadsheet

### ISSUE THREAD

**Issue by anabeabas** [benwbrum/fromthepage#4026]
We got an email from a transcriber asking for the formula bar at the top of spreadsheets. She says that it's easier to make corrections to a cell there since she currently has to delete the contents of a cell and retype the whole content.

**Comment by benwbrum** [comment]
According to research by @atbah,  the current version of Handsontable which the project is using is 6.2.2 and no formula plugin support for 8.x.x and lower.
In order to use formula plugin, we should upgrade the Handsontable to the latest one.
Also, it needs a license key to use formula plugin.
https://handsontable.com/docs/javascript-data-grid/formula-calculation/ 

Since we can't include closed-source code in FromThePage, I'm closing this as not planned.
