### ISSUE TITLE
"Pages transcribed" in statistics tab off

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#411]
Not sure what this is currently pulling from, but we've started transcribing 2 pages and they are not showing up in the "pages transcribed" statistics in the statistics tab.  May be related to #213 .

@suwiding

**Comment by tbl73** [comment]
This seems to be pulling the info okay on my test server, so a couple of questions:   Is anything showing up in the statistic?  Is there more than one work?  Who is the owner of the collection?

**Comment by tbl73** [comment]
Is this related to #365, which hasn't been merged into production yet?

**Comment by saracarl** [comment]
@benwbrum and I brainstormed some ideas for fixing this.  

1)  one approach is turning off the revisioning during the import
wonder if we start with revision 0 or 1
if we start with 1, we could make a revision 0 for the IA work

2)  OR take a look at the code that determines whether a page edit is a transcription or not
Rather than driving that logic off of page version, we could look at the previous version's source_text and see whether it was blank.

3)  It may also be worth investigating why we are doing multiple versions for IA import?  Maybe it's the titling based on OCR?  Perhaps that's done in a second pass?
If we could keep it from generating the 2nd version, it'd both fix the deeds and whatever funkiness I imagine shows up on the version/diff view

**Comment by tbl73** [comment]
I was digging further into this, trying to figure out where exactly the multiple versions are coming from.  Pages do start from revision 0, and they're set up (in the model) so that a new page version is created after each save (which makes sense).   I think what's happening is that the page is being saved twice during the conversion process, and so it's getting both version 0 (which is expected) and version 1 (which is not).  I think the relevant saves are in  line 84 and line 87 of the convert_to_work method in the ia_work model.  
So I don't know how exactly you could stop it doing two versions with the current setup unless you don't need both saves. (Though I agree, the version/diff view looks a little weird now, too.)

**Comment by tbl73** [comment]
See #447 for some related issues.

**Comment by tbl73** [comment]
Pushed up code in ia-stats.
