### ISSUE TITLE
Work Pages Tab link to page throws 500 error

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#4158]
As a project owner:
* Click on a work
* Click on the `Pages` tab
* Click on a page title in the left-hand side of the page listing

This results in a 500 error.

Looking in the logs, we see this exception:
```
ActionController::UrlGenerationError at /benwbrum/ai-assist-sandbox/page-notes/emily-caroline-creaghe-diary-22-dec-1882-5-sept-1883-2946fa12-d861-43f8-95be-6a412b2d1286/33267694
No route matches {:action=>"show", :controller=>"thredded/messageboard_groups", :id=>nil}, possible unmatched constraints: [:id]
Did you mean?  show_messageboard_group_url
```
![Screenshot from 2024-06-14 11-48-59](https://github.com/benwbrum/fromthepage/assets/199961/0d276874-842b-4c18-a231-7297c25251e1)

**Comment by WillNigel23** [comment]
Upon further investigation, this problem occurs when @collection.messageboard_group is nil. Can you provide more details as to

1. what is a messageboard_group
2. what to do in case it does not exist
3. I tried passing @collection.id instead and I got the error that the messageboard_group has been disabled for the collection. Is there some sort of settings to enable for this or this error is purely due to me using collection id (probably the latter, but just to confirm)

@benwbrum  @saracarl

**Comment by WillNigel23** [comment]
Updates on PR #4169
