### ISSUE TITLE
skipping subject classification when marking page as done

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#4165]
If you have new subject links on pages, we insert a "categorize new subjects" step after a page is saved.

With the new "done and move to the next page" functionality, we are skipping that step.

@benwbrum can weigh in more, but we think if you have subjects you are in a "documentary editing" flow rather than a transcription flow, and we should both do the "categorize new subjects" step and *stay* on the page to continue editing.

Samara at Dartmouth reported this today.

**Comment by benwbrum** [comment]
For background on subject linking, see [this video](https://www.youtube.com/watch?v=NLXwwmLoB_c)

Samara at Dartmouth reports a new behavior she sees today:

> When she reviews a page and adds a subject link, pressing "Approve" saves the page and advances her to the next page, without letting her assign the new subject to a category.

Background:
* 5-10% of projects do not merely transcribe text, but also create an index of subjects within the text using wikilinks 
* Generally, indexing happens after transcription is finished, rather than during the transcription process.    
* The person indexing often makes multiple edits to the page as they research people or places mentioned within that page
* When a new subject is indexed, we (normally) ask users to categorize any subjects on that page that have not yet been categorized.
* Historically, saving a page always redirected to `transcribe#assign_categories` -- if there were no subjects to categorize, the `assign_categories` action would simply redirect the browser to the appropriate page.
