### ISSUE TITLE
adding collaborators doesn't refresh the list in the UI

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#4211]
If you add a collaborator in the collection settings, i.e. https://fromthepage.com/sylvia-kollar/1890-police-census/edit/privacy#
the list doesn't refresh.

(Please check for the same thing in owners)

**Comment by WillNigel23** [comment]
As per discussion, list works correctly.

Probable cause of confusion here is the 'x' button, where clicking that closes the modal without page refresh and thus user might feel like the list did not update.

As per discussion, we will remove the 'x' button for collaborators modals so that users are forced to click `Done` instead.

@saracarl @benwbrum
