### ISSUE TITLE
Page-level categorization

### ISSUE THREAD

**Issue by Simon-Dirks** [benwbrum/fromthepage#4220]
Dear FromThePage team,

Thank you so much for the beautiful project! We are self-hosting an instance at Utrecht University (The Netherlands) with the card index system of the American philosopher Susanne Langer.

Though we're very happy with subject indexing functionality (e.g., to label people, places, etc), I could not find any functionality to similarly **assign "categories" at the page/scan-level.**

As an example: It would be of major added value for us if we could label "card index dividers", "biographical cards", "shopping lists", etc. I imagine functionality that looks very similar to categorizing subjects, with a multi-select dropdown:
![image](https://github.com/benwbrum/fromthepage/assets/2639851/afbb7409-c0dc-4583-9dc2-565f02ca0c20)

Is there already something written for this? Or, if not, any pointers on how to get started?

Wishing you all the best!

-Simon

**Comment by benwbrum** [comment]
Hi Simon,

It's great to hear that Utrecht University is using FromThePage!  We'll have to add a new pin to our map of global open-source installations.

Are you using field-based transcription or document-based transcription for the project?  If the collection is field-based, I would just add a new field for the type of page.

If you are using document-based transcription--and it sounds like this may be the case, since subject indexing is only available in that workflow--there is really no way to categorize individual pages in the way you describe.  That said, if these different lists are divided into separate FromThePage works, you could use metadata description to classify each work by type of document, as [Dartmouth University is doing with their Wrangel Island project](https://fromthepage.com/dartmouthlibrary/wrangelisland/stefansson-wrangel-09-30-001/describe).

**Comment by Simon-Dirks** [comment]
Update: Managed to figure it out! Used a similar approach as for the `page_article_links` db table. I'm assuming you're not interested in this feature for the project as a whole (let me know if otherwise!), so closing the issue for now.
