### ISSUE TITLE
rake tasks execute their logic twice

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#4271]
Karmine says:

> For several months I have been receiving two “Recent Activity in Your Collections” emails whenever someone works on one of our projects. A few days ago this multiplied to four. Can you please look into this and see if you can reduce it to one?

**Comment by saracarl** [comment]
So checking our smtp service (postmark), I see two emails going out, 20 minutes apart:
![image](https://github.com/user-attachments/assets/3a082292-2441-4581-a347-fe8645c1b8dc)

There is only a crontab for `fromthepage` and it only calls the rake task once:
```
fromthepage@fromthepage:~$ sudo ls /var/spool/cron/crontabs/
fromthepage
fromthepage@fromthepage:~$ sudo grep collection_stats /var/spool/cron/crontabs/fromthepage
00 3 * * * /bin/bash -l -c 'cd /home/fromthepage/deployment/current && RAILS_ENV=production bundle exec rake fromthepage:collection_stats_by_owner >> /tmp/cron_log_file3 2>&1'
```
This is confirmed by the syslog of the cron calls (one on 8/25, one on 8/26):
```
fromthepage@fromthepage:~$ sudo grep collection_stats /var/log/syslog
2024-08-25T03:00:01.416707+00:00 fromthepage CRON[1342498]: (fromthepage) CMD (/bin/bash -l -c 'cd /home/fromthepage/deployment/current && RAILS_ENV=production bundle exec rake fromthepage:collection_stats_by_owner >> /tmp/cron_log_file3 2>&1')
2024-08-26T03:00:01.102433+00:00 fromthepage CRON[1557855]: (fromthepage) CMD (/bin/bash -l -c 'cd /home/fromthepage/deployment/current && RAILS_ENV=production bundle exec rake fromthepage:collection_stats_by_owner >> /tmp/cron_log_file3 2>&1')
```

This points to the application code.  

There are 2 changes -- a tab and a exception catching block -- in send_owner_emails.rake:
https://github.com/benwbrum/fromthepage/blame/development/lib/tasks/send_owner_emails.rake#L3

The relevant part of the admin mailer hasn't changed in 5 years:
https://github.com/benwbrum/fromthepage/blame/d160dd76fd39fe50e190e24b2f659adbae7734d8/app/mailers/admin_mailer.rb#L31

The change to postmark on June 26th also seems like a probable introduction of a problem.  Here's that PR:
https://github.com/benwbrum/fromthepage/pull/4176/files

I confirmed the action_mailer settings in production.rb matched the changes in the PR:
```
  config.action_mailer.default_url_options = { host: 'fromthepage.com' }
  config.action_mailer.default_options = { from: 'support@fromthepage.com' }
  config.action_mailer.delivery_method = :postmark

  config.action_mailer.postmark_settings = {
    api_token: 'XXXX'
  }
```

**Comment by saracarl** [comment]
We're getting duplicates for the admin emails as well, so I ran that:
`/bin/bash -l -c 'cd /home/fromthepage/deployment/current && RAILS_ENV=production bundle exec rake fromthepage:email_stats[24] `
and it also created duplicate emails.

This means:

- it's not a system level (cron, etc) problem
- it's not a task level (rake or task code) problem, including the exception handling I mentioned earlier
- it must be a fromthepage code level thing, I think.  


Ben checked, and the duplicates started on August 7th.  That's well after the June 26th postmark change.

**Comment by benwbrum** [comment]
It turns out that ever since #4259 and #4264 were deployed, rake tasks have been executing their logic twice.  

We initially noticed this problem for nightly activity emails which are sent by cron jobs.
We also notice this when observing sync to CONTENTdm attempting to send each page's transcript twice (#4277)
We just got a report of this happening when importing documents from CONTENTdm, so were able to duplicate the problem as follows:

* Go to a collection you own
* Click Add Work
* Click Import from CONTENTdm
* Click Import Several Individual Compound Objects
* Paste this compound object URL into the textarea: https://earchives.lib.purdue.edu/digital/collection/epurdue/id/725/rec/3
* Press Import
You should only get a single letter imported into your collection, but instead you get two!

We suspect that this is related to the change to make `process_document_upload` use ActiveJob, which seemed to add a lot of duplicate declaration messages to rake task initializations
