### ISSUE TITLE
[FTP UT library install] 500 error on Editor dashboard

### ISSUE THREAD

**Issue by atomrab** [benwbrum/fromthepage#441]
Admin and Owner dashboards are working for me fine as a logged-in user on the library instance, but now when I select the "Editor" dashboard, I get a 500 internal server error (this is the page URL: https://fromthepage.lib.utexas.edu/dashboard/watchlist).

**Comment by tbl73** [comment]
I think this got duplicated in issue #442; I just pushed up some changes for review to hopefully resolve this problem.

**Comment by saracarl** [comment]
This is fixed in the current version of the master branch of FtP; I'm waiting to send Perry an email to upgrade until we get the start project issue -- #348 -- fixed.  You are welcome to upgrade/ask Perry to upgrade if this one is more important than the start project issue and affecting your day-to-day work.  (I don't have a good grasp of how important it is.)

**Comment by tbl73** [comment]
This is resolved; see #442 for more information.
