### ISSUE TITLE
Mobile ingestion

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#458]
Mobile is 80% there, but needs to be fleshed out, tested, bugs fixed, and documented.

online mobile -- use camera
offline mobile -- scan to pdf
document how to 

See also #255 and #257

**Comment by tbl73** [comment]
In issue #460, we discussed the "add pages" action for an empty work.  The modal currently has options to "Cancel", "Save & New Work" and "Save & Next Page".  It isn't entirely clear what you should do if you're finished with adding pages but don't want to create another work.  This functionality is essentially only used in mobile, so we're adding it to this issue, rather than having it as part of #460.

**Comment by saracarl** [comment]
Closing until we decide to focus on mobile as a feature.
