### ISSUE TITLE
Option to disable subject feature

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#501]
We need the ability to turn off subject linking. 

-- available on a collection basis
-- I'd do it as a checkbox under "footnotes" and before "manage works" on the collection settings page
-- It should hide the "subjects" tab for a collection
-- It should hide the "autolink" button on the transcription screen
-- hide the following text on the transcription screen:
"Autolink" will suggest subjects certain words could be linked to or you can use double braces to link subjects. [[Jane Doe]] will link the text "Jane Doe" to the subject Jane Doe, while [[Jane Doe|Jane]] will link the text "Jane" to the subject Jane Doe. We recommend that linking be left to an editor after the initial transcription is made.

View helper that takes the xml text and turns it into a href anchor tag.  The view helper should check and see if subjects are enabled.  If they are not, then do not create the link in the view.  

Note that if you have subjects originally, then disable them, you could still get to the "normal" subject page by typing in the URL for it.  We've decided that is OK.  (We are not checking the setting on display of the subject page.)

Feel free to break this into multiple work items/issues.

**Comment by saracarl** [comment]
Also need:

disable the Subject Categories on the collection main page
here at the bottom for example:
http://fromthepage.com/JuliaBrumfield

Hide top indexers list
Hide Disable percent indexed in work progress bar

Collection statistics page:
        Disable subjects
        Disable mentions
        Disable pages indexed
        Disable top indexers and percent indexed (as above)

Work read page:
        Disable category navigation on side panel
    Work contents page:
        Suppress “annotate” button by unindexed pages

 Work help Page:
        Move help text contents from page_block into template
        Disable indexing instructions within template.

**Comment by tbl73** [comment]
Since this is such a lot of little pieces, here's a list of all the different things that were changed and which file they were changed in.  It includes all the things listed above plus a couple of additional pieces.

-  Collection settings - "disable subject indexing" checkbox - app/views/collection/edit.html.slim
-  Migration to add subjects_disabled column so this can be set at the collection level - db/migrate/20170111143351_add_subjects_disabled_to_collections.rb

 When subjects are disabled: 
- Collection overview 
     - remove subject categories
     - Remove % indexed from work stats and progress bar (color changed) - app/views/collection/show.html.slim & - app/models/collection.rb
- Collection - hide subjects tab - app/views/shared/_collection_tabs.html.slim
- Collection - statistics: remove Subjects, References, Pages Indexed
 	- Last 7 days stats - remove references, new subjects
 	- Work Progress: remove % indexed and changed bar
 	- Collaborators: remove Indexing - app/views/statistics/collection.html.slim
- Collection - Export: remove Export Subject Index - app/views/export/index.html.slim
- Collection - Collaborators - Hide recent subjects section - app/views/collection/_contributors_body.html.slim
- Work - Overview - remove Categories sidebar - app/views/display/_multi_page.html.slim
- Work - Help - already was a template, hide linking instructions - app/views/static/transcribe_help.html.slim
- Work - Contents - hide annotate button by unindexed pages - app/views/display/list_pages.html.slim
- Page - Transcribe - remove Autolink button - app/views/transcribe/display_page.html.slim
- Page - Translate - remove Autolink button - app/views/transcribe/translate.html.slim
- Page - Transcribe - instructions:  remove Autolink instructions - app/views/shared/_markup_help.html.erb
- Abstract_xml_helper - suppress the mechanism that turns that xml into links in the html - app/helpers/abstract_xml_helper.rb

**Comment by tbl73** [comment]
Additional changes:
- added method to document sets to support subjects_disabled
- Collections page (dashboard/index) - hide indexing in lists of works
