### ISSUE TITLE
ocr_correction deeds need to be added to "recent edits" for a collection

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#511]
I just edited a page in a work that had OCR imported data.  The correction shows up in the statistics and my activity stream on my dashboard, but doesn't show up in the collection page's "recent edits" stream.  It needs to.  

This page:
http://localhost:3000/collection/show?collection_id=4

wording should be "user corrected XXX page"

**Comment by tbl73** [comment]
@saracarl : Question on this - in the collection page's "recent edits" stream, right now any activity - transcription, edit, article-edit -  shows up as "user edited xxx page".  I've added correction deeds, so they're included now, but do you want all of the wording changed for that activity stream, so that it says the type of activity rather than just edited?

**Comment by saracarl** [comment]
I think we are fine with just "edited" for any purpose there.

Sara

**Comment by tbl73** [comment]
I switched to another collection, and  it looks like it's using the correct wording after all - must have been something funny in that test collection.
