### ISSUE TITLE
invite to transcribe

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#623]
We need a way for work/collection owners to enter in a list of email addresses and invite their "crowd" to transcribe the project.  

Need a good template email, which they could modify, that includes a link directly to the work/collection.

If we wanted to get fancy we could track which invitations were accepted and turned into users/transcribers.  I wonder if there is a gem for this?
https://github.com/tomichj/invitation 
Might work, but we'd need to think through user permissions as well.

**Comment by benwbrum** [comment]
We need to make sure that any feature within the system which 1) accepts an email address as a target, and 2) accepts some user-entered data, is only available to project owners who are not trial users.  A previous employer had several visits by the Secret Service because anonymous users were sending death threats to public officials via such a capability.
