### ISSUE TITLE
Cleanup old uploaded image files

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#626]
these are in public/uploads/document_upload/file/{not process log}

**Comment by tbl73** [comment]
These are the actual documents that are uploaded, rather than the image files that are created per work.  Moving forward, they'll be deleted after a successful upload, but the older ones need to be cleaned up, either manually or via a script.
#602 is referring to the page image files that weren't being deleted when a work was deleted.  They'll be deleted in an after_destroy callback moving forward.  The older ones will also need to be cleaned up.

**Comment by saracarl** [comment]
verified.
