### ISSUE TITLE
Subject graphing in document sets

### ISSUE THREAD

**Issue by tbl73** [benwbrum/fromthepage#674]
We need to think through the code for subject graphing and possible duplicates of subjects within a document set, so that it's displaying the subjects for a document set rather than the collection as a whole.

**Comment by benwbrum** [comment]
The graph is generated by `article_controller`, looking at the `page_article_links` table.  We should be able to filter this query by works within the document set.   

This will require some load testing, since at present I believe that the `page_article_links` table only contains `page_id`, and filtering by `page_id IN ([enormous list of all pages in all works in the document set])` is likely to break.  If necessary, we can denormalize the `work_id` onto the `page_article_links` table and use that to filter.  That will require a migration and changes to the code which populates the table (maybe `AbstractXmlProcessor`?).
