### ISSUE TITLE
don't fail upload if smtp not configured

### ISSUE THREAD

**Issue by atomrab** [benwbrum/fromthepage#682]
When an owner tries to upload a zip file to an existing collection, the "Browse" pathway renders as e.g. C:\fakepath\Archive2.zip, and when the owner clicks the "Upload File" button, the interface returns a 500 Internal Server error. It is not possible to edit the filepath to see if this is the problem (any action in that field after a file has been browsed to triggers a new browse-to-file window).

Is this something going on with our server, or is it a bug in the interface?

**Comment by saracarl** [comment]
I suspect it's a configuration issue.  It looks like the SMTP (mailer) configuration was either wiped out by a recent upgrade or the upgrade got the code to the point where the mailer is required.  

I, [2017-06-22T15:50:29.504327 #2286]  INFO -- : Completed 500 Internal Server Error in 443ms
F, [2017-06-22T15:50:29.506410 #2286] FATAL -- : 
Net::SMTPFatalError (554 Message rejected: Email address is not verified. The following identities failed the check in region US-WEST-2: support@fromthepage.com
):
  app/helpers/add_work_helper.rb:35:in `new_upload'

It should be a pretty fast fix for someone who knows the SMTP settings UT uses and can log into the server.  See step 3 of the following document : 
https://github.com/benwbrum/fromthepage/wiki/Configuring-FromThePage-For-Your-Environment

Or I can look over the config/environments/production.rb file and see what looks to be the problem. (send it via email rather than posting it here).

**Comment by saracarl** [comment]
And I think once we get this specific issue resolved we should fix the code path that causes uploads to fail without a successful email -- this is the second time in as many weeks I've had this problem happen in a customer environment.

**Comment by tbl73** [comment]
Question - do you still want those system mails to get sent if a document is uploaded?  (I'll change the code so an unsuccessful email doesn't break the upload process, but should they get sent in general?)

**Comment by saracarl** [comment]
Yes, emails should be sent on a successful upload. 

Sara
