### ISSUE TITLE
collaborators can't export

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#700]
Should they be able to?

**Comment by saracarl** [comment]
Yes, they should be able to.  @tbl73 can you review how much work this would be -- it seems easy to me, but I want to make sure.

**Comment by tbl73** [comment]
Should be pretty straightforward - they just don't see the tab at the moment, rather than actually being restricted from the page.  Should they have access to any other "owner" tabs?  It looks like collection collaborators only see Overview/Statistics/Subjects for a private collection at the moment.

**Comment by saracarl** [comment]
@benwbrum we need to think about this one.

**Comment by saracarl** [comment]
Do you get only the pages you worked on, or the entire work?

**Comment by benwbrum** [comment]
Folded into #2395
