### ISSUE TITLE
duplicates on tracking

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#791]
We're getting a lot of errors like this, at least on the zebrapedia server, and possibly on the others:

E, [2017-09-25T16:33:35.647645 #35725] ERROR -- : Mysql2::Error: Duplicate entry '1f15e7c8-268f-4135-82ec-057bdb4effd3' for key 'index_visits_on_visit_token': INSERT INTO `visits` (`browser`, `city`, `country`, `device_type`, `ip`, `landing_page`, `latitude`, `longitude`, `os`, `postal_code`, `referrer`, `referring_domain`, `region`, `started_at`, `user_agent`, `user_id`, `visit_token`, `visitor_token`) VALUES ('Chrome', 'State College', 'United States', 'Desktop', '216.169.176.130', 'http://zebrapedia.psu.edu/collection/edit?collection_id=1', 40, -77, 'Windows 7', '16801', 'http://zebrapedia.psu.edu/collection/edit?collection_id=1', 'zebrapedia.psu.edu', 'Pennsylvania', '2017-09-25 20:33:35', 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36', 1, '1f15e7c8-268f-4135-82ec-057bdb4effd3', '7b90a609-1806-4b1c-a04d-4de27983c805')

**Comment by tbl73** [comment]
I get them on my dev database, too, FYI.

**Comment by bencomp** [comment]
I see these errors too. It looks like they are related to ankane/ahoy#34. Unfortunately it doesn't appear to have been solved. Maybe upgrading to version 2 helps?

Or, looking at the commit message of https://github.com/ankane/ahoy/commit/0085e70ceff1a690d1cc5958cb6cd0a81ef7b5a5, there should not be a direct call to `ahoy.track_visit` in `application_controller#track_action` because (I'm really just guessing here) Ahoy is already called at some point.

It's not really an issue for us at this point, but (of course) I would like to have a clean log. :)

**Comment by aaronlifton2** [comment]
Still a problem.

**Comment by saracarl** [comment]
This was resolved by #1333, by doing as @bencomp said and getting rid of the direct call to `ahoy.track_visit` in `application_controller#track_action`.
