### ISSUE TITLE
ActiveRecord SQL error ORDER BY clause not in SELECT, incompatible with DISTINCT

### ISSUE THREAD

**Issue by bencomp** [benwbrum/fromthepage#806]
When running FromThePage with MySQL 5.7.19 (after applying a patch for #349), I get errors when requesting the Dashboard or Collections views like `Mysql2::Error: Expression #1 of ORDER BY clause is not in SELECT list`. It appears to be caused by a change of MySQL's SQL mode, as explained in rails/rails#25924.

When I add the variable suggested in that issue to the database.yml config, the error goes away. However, I don't know what impact a change like this has on older MySQL versions. Changing the queries might be a better solution for the long term.

**Comment by benwbrum** [comment]
Let's see about adding this to our default `database.yml` file: `sql_mode: TRADITIONAL`, run our tests, and see what happens.

**Comment by tbl73** [comment]
We added this as part of getting Travis-CI to work with multiple databases; closing.

**Comment by tbl73** [comment]
The traditional mode seems to work fine with MySQL 5.7, and we're planning to keep it that way for the time being.  We do a lot of queries on associations with both distinct and order by, which break with the change.  Some documentation of the changes that would be needed if/when we move away from traditional mode:
I set a default scope on the deeds model: default_scope { order(created_at: :desc)} which allows us to get deeds in order rather than adding that as an order clause for the display of deeds. (In certain cases such as the contributor helper, you then need to add unscoped to get the deeds created in a certain time period - i.e. recent_trans_deeds = transcription_deeds.unscoped.where("created_at >= ?", start_date).distinct.pluck(:user_id) .
Many of the pluck queries have to be changed to map instead: for example, the new_contributors method in the contributor helper changes from "user_deeds = @collection.deeds.where(condition, start_date, end_date).distinct.pluck(:user_id)" to  "user_deeds = @collection.deeds.where(condition, start_date, end_date).distinct.map(&:user_id)".  Another example is in the Collaborator Dashboard -
 in the recent work method: "recent_deed_ids = Deed.joins(:collection, :work).merge(Collection.unrestricted).merge(Work.unrestricted) .where("work_id is not null").order('created_at desc').distinct.limit(5).pluck(:work_id)" changes to "recent_deed_ids = Deed.joins(:collection, :work).merge(Collection.unrestricted).merge(Work.unrestricted).where.not(work_id: nil).distinct.limit(5).map(&:work_id)"
More changes would be required as well.
