### ISSUE TITLE
Pagination/Hide Transcribed Works problems

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#864]
We're getting weird interactions between pagination and hiding transcribed works in the case where we have a lot of works in a collection.  

Example:
https://fromthepage.com/digitalindy/indianapolis-metropolitan-police-department

It shows nothing, because the first 10 are already fully transcribed, but there are plenty of works in later pagination sets that aren't transcribed.

**Comment by tbl73** [comment]
I'm not entirely sure how we're going to be able to fix this with the current set up.  The pagination is done server side, but the hiding is done client side (because you wanted the works to actually be there for webcrawling; just not visible).  I agree it looks weird, though - we'll have to think on how to change it.  Maybe they should be sorted differently before pagination?  The large collections PR makes it possible to sort by percent complete, which might help.

**Comment by saracarl** [comment]
We think that the best way to handle this is to switch the checkbox to a button, which will post to the server, and re-render the work list with a different query.  Handling this server-side would fix the pagination problems.

**Comment by tbl73** [comment]
So just to clarify, you -don't- want to have all the works available for web crawling by default?  That's the main reason this is happening - they're hidden rather than not being in the query because of the crawling.  (I do agree it looks weird and this would make it look better. I don't actually think it needs to be changed from a checkbox to be re-rendered server side; the problem has more to do with the original goal than anything else.)

**Comment by saracarl** [comment]
if we make it [show completed works] a link that's styled as a button, then crawlers will be able to click it and see the results.
