### ISSUE TITLE
field based: extra columns in csv export?

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#903]
We seem to have duplicate columns (beyond verbatim and subject links) in the csv export for tables/fields.

**Comment by tbl73** [comment]
Can you show me an example?  I'm not seeing it in my test exports.

**Comment by tbl73** [comment]
It turns out this is happening in field-based table exports, not in pure markdown table-based exports, which is why I didn't see it in that test export.  One of the goals was to be able to export tables within fields (for the possibility of mixed transcriptions), and it looks like I need to work on that part some more.
