### ISSUE TITLE
wordpress template to match product

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#93]

**Comment by saracarl** [comment]
Nick, have you done wordpress templates before?  We need one that matches the product...

**Comment by saracarl** [comment]
Should include the logo.  Needs to be able to run on a separate server from the app, but be a good front end for it.  We'll use it for marketing and support pages/information.

**Comment by kolking** [comment]
@saracarl I'm not very familiar with wordpress themes but there is nothing difficult for me. I think the best way we should do it is the following:
1. You run a wordpress installation on a separate server with a default theme
2. You set it up and configure like you want - everything expect the design
3. After that you'll provide me with the access to the installation so I can work on design

**Comment by kolking** [comment]
http://fromthepage.wpengine.com/

**Comment by benwbrum** [comment]
This looks reqlly good, but I have one question.  If I log onto wordpress and go to edit the site's homepage http://fromthepage.wpengine.com/wp-admin/post.php?post=5&action=edit I don't see the page that's displayed at http://fromthepage.wpengine.com/ .  Where is that content coming from, and how can I change it to e.g. add links to the app?

**Comment by kolking** [comment]
@benwbrum you can edit the HTML code of this page here: Appearance -> Editor -> front-page.php (http://fromthepage.wpengine.com/wp-admin/theme-editor.php?file=front-page.php&theme=fromthepage)
Images can be edited in the Media Library (http://fromthepage.wpengine.com/wp-admin/upload.php) so when you need to change them, simply replace the existing images.
If you want, I can try to search for a plugin to split the home page into a number of text blocks and separate them from the layout code. In that case you'll be able to edit these text blocks using WYSIWYG instead of code editor.

**Comment by benwbrum** [comment]
Thanks, Nick!  I'm comfortable with the code, now that I know where to find
it.

Ben
