### ISSUE TITLE
collection collaborators "add" button greyed out

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#944]
If you try to add a collaborator to a private collection (not an owner) the "add" button is greyed out.  (this is field based transcription, in case that matters).

**Comment by tbl73** [comment]
I haven't had a chance to look into this yet, but I suspect it's related to that same jquery problem I just fixed when I added the email identifiers in PR #923 .  (Enabling the button was being done through jquery, which wasn't working for field-based transcriptions).  Although I changed the behavior so that the button was just enabled.)

**Comment by tbl73** [comment]
It's not happening for me in the latest version of ui-design, which includes PR #923 - once they get that version of the code, the button shouldn't be greyed out.

**Comment by saracarl** [comment]
Yep, that fixed it.  Thanks.
