### ISSUE TITLE
IIIF Import fails on Portal manifests

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#953]
The IIIF import fails on this manifest imported from the Portal to Texas History:
`https://texashistory.unt.edu/ark:/67531/metapth974141/manifest/`

The problem is that, when we try to figure out where to put the manifest in a parent collection, we look at the `within` element for a manifest with an `@id`:

```
    32:       find_parent = @sc_manifest.service["within"]
 => 33:       if find_parent.nil?
    34:         @sc_collection = nil
    35:       else
    36:         parent_at_id = @sc_manifest.service["within"]["@id"]
```

This fails on this manifest (which is syntactically) because its within element looks like this:
```

   "within":[
      "https://texashistory.unt.edu/explore/collections/THC/top/",
      "https://texashistory.unt.edu/explore/partners/STTICO/top/"
   ],
```

We need to handle this gracefully instead of rejecting the manifest.  Probably just changing our conditional to `find_parent.nil? || @sc_manifest.service["within"]["@id"].nil?` would fix it.

**Comment by tbl73** [comment]
The @sc_manifest.service["within"]["@id"] call doesn't work, because "within" returns an array - if I test for it being an array rather than a presentation collection, the import works.  Is there any other kind of result that could be returned when you look at the within element (to make sure we're testing for everything)?
