### ISSUE TITLE
AddPagesXmlTextIndexAgain migration fails on utf8 database...

### ISSUE THREAD

**Issue by digitalmoksha** [benwbrum/fromthepage#98]
While trying to do a new install of FromThePage, I ran across this problem.  If you start out with a utf8 MySQL database (as most people will these days), then the AddPagesXmlTextIndexAgain migration fails with a "Mysql2::Error: Specified key was too long; max key length is 1000 bytes".

This is due to a long running bug/issue in MySQL where the max key length can only 1000 bytes, but since they calculate each utf8 character as 3 bytes, the max number of utf8 characters is 333.

[http://bugs.mysql.com/bug.php?id=4541](http://bugs.mysql.com/bug.php?id=4541)

I see you're doing a lot of upgrades on the code, so wanted to bring this to your attention.

Cheers,
Brett

**Comment by jbaiter** [comment]
Has this been fixed? I just tried installing from the master branch on an up-to date Ubuntu 16.04 and am getting this exact error.

**Comment by benwbrum** [comment]
To our knowledge it works now.
@saracarl just did a fresh install yesterday, and I don't think this
problem occurred.

Can you tell us which version of MySQL you are running?

**Comment by jbaiter** [comment]
I'm trying to install it via Docker: https://github.com/jbaiter/docker_fromthepage
The version is `mysqld  Ver 5.7.15-0ubuntu0.16.04.1 for Linux on x86_64 ((Ubuntu))`.

To reproduce, just clone the above repository and run `docker build .`. Note that I'm using a fromthepage fork that uses a more recent version of the `mysql2` dependency, since the current version is incompatible with Mysql 5.7.

**Comment by saracarl** [comment]
Hi @jbaiter  --  I'm looking into this.  So far I think this index is not being used (it was used in a previous full text search solution that has since been replaced), but let me look through the code to confirm that.

If you wanted to experiment, you could comment out the line in the migration that adds the index:  

    add_index "pages", ["xml_text"], :name => "pages_xml_text_index", :length => 1000

I'd be curious if this is the only place we run into a problem with mysql 5.7.   We're running version: 5.5.52-0+deb8u1 (Debian), so we haven't done any testing with more recent versions of mysql.

**Comment by saracarl** [comment]
Ok.  We're fine getting rid of that index completely.  Here's the commit where @benwbrum rewrote the fulltext search functionality:
https://github.com/benwbrum/fromthepage/commit/d57626aae7d917746987cbcecb0caebb29c5e313
It now uses search_text instead of xml_text.

I also checked and the new search_text field doesn't have a length specified on the index:
https://github.com/benwbrum/fromthepage/blob/3ac52742769b306870a75aff40177e202beb44c0/db/migrate/20150115152502_add_search_text_to_page.rb

The simple solution is to edit 
db/migrate/20130324195452_add_pages_xml_text_index_again.rb
And comment out 
add_index "pages", ["xml_text"], :name => "pages_xml_text_index", :length => 1000

The better solution is to do the above AND create a new conditional migration that drops the index for any environment that has it so all environments are in sync.

@jbaiter you are welcome to do this and create a pull request, or we can get to it next week.

**Comment by tbl73** [comment]
I commented out that old migration and added a new conditional migration to drop the index if it is there.  Pushed up in the migrations branch.

**Comment by jbaiter** [comment]
Thank you, that does indeed fix the migration! Sorry for not responding more promptly :/
